### ISSUE TITLE
[Suggestion] Add contact me

### ISSUE THREAD

**Issue by soywod** [cnvs/canvas#142]
Here a little problematic : if I dont like using social networks, how a potential customer/company can contact me from the blog ? Is there a possibility to show email / phone number ? If not, what do you think about a new envelop icon next to social networks that redirect to a contact form, or redirect to a `mailto:xxx@xx.com` ?

**Comment by austintoddj** [comment]
Good idea @soywod. I'll see what I can do to throw this feature in the next release. 

Quick thought: it sounds like a potential new feature for Canvas would be to have a one-page portfolio part of the blog. So, hitting the '/' route of the application would go to a single page portfolio of the author. It may be a more well-rounded application then for developers to have a portfolio and blog all in one. This could open up a lot more possibilities of what the author could feature on their site. What do you think?

**Comment by soywod** [comment]
That's how I use your application on (soywod.fr)[http://soywod.fr], I named it blogfolio :p and I've created a tag portfolio, and when you click on the tag I can see all articles that have the portfolio tag (so the user have an overview of my portfolio) but it's not intuitive. If portfolio + blog + contact if different page, we should put a menu ?

**Comment by soywod** [comment]
Suggestion : If you hit the `/` route, you reach an "about me" page, showing informations about the developer (like the author part in to the bottom of each article) with a button "My portfolio" that redirects to `/blog?tag=portfolio` (to see all posts with tag portfolio). Then you have the X last posts of your blog, with a button "Show all posts" that redirect to the "/blog"

**Comment by austintoddj** [comment]
That's a good idea @soywod. I didn't think of the fact that you could just tag posts with the `portfolio` tag and that would suffice. But that actually sounds perfect. I wonder, there would most likely need to be a way to enable/disable that from the admin section, because some people may just want a straight blog, without having the About Me page. Would you agree?

**Comment by soywod** [comment]
Yeah perfect ! Totally agreed. I'll PR something and we'll discuss about ;)

**Comment by Vviizard** [comment]
Why not add an Imprint/Impressum route?
A pure "About Me" page wouldn't satisfy the _Telemediengesetz_, but an imprint would satisfy what has been suggested in the original comment.

**Comment by austintoddj** [comment]
@Vviizard Not familiar with what * Telemediengesetz* is. Could you clarify?

**Comment by Vviizard** [comment]
It's a german law that requires websites/website owners to disclose contact information of the content publisher, see [here](https://en.wikipedia.org/wiki/Impressum).

**Comment by austintoddj** [comment]
Thanks for the link. I believe a popup with the author information, contact info(email, social media/etc.) would be sufficient for this. Do you think otherwise? @Vviizard

**Comment by Vviizard** [comment]
The generally accepted practice is using something like `/imprint` or `/impressum`. It may contain the following information
- Name and full address of the person responsible for the websites journalistic content
- Name, address, email-address, phone/fax of the website owner
- Privacy Statement/Policies, including privacy statements for external services, such as Goolge Analytics, Disqus etc.
- Disclaimer for content and links.

Give me a sec to make a sample @austintoddj

**Comment by Vviizard** [comment]
http://blog.vviizard.eu/blog/german-imprint-example 
Generated by https://www.e-recht24.de/impressum-generator.html
(This is obviously a lot longer, because I added all optional disclaimers available)

**Comment by Vviizard** [comment]
I think a good way to implement this would be to just offer the optional routes `/imprint` and `/privacy` and make them editable like a blogpost.

**Comment by austintoddj** [comment]
@Vviizard Thanks for making that example. I'll do a little more research on this and see what we can do. Till then, perhaps just adding a blog post with this info, like you did there, would be sufficient for German website laws?

@soywod Any update on the author popup?

**Comment by Vviizard** [comment]
@austintoddj The Imprint must be available within 2 clicks from anywhere on the site, so it'd be best to put it into the footer.
Also, I should open a seperate issue for the [EU cookie law](https://www.cookielaw.org/the-cookie-law/).

**Comment by Vviizard** [comment]
You could also offer something like Tumblr does: Pages. You can choose a custom route and then one of three types: `Redirect`, `Standard Layout` (uses standard blog post layout, but isn't actually a post) and `Custom Layout` (which is a completely custom HTML page).

**Comment by austintoddj** [comment]
That's not a bad idea @Vviizard, adding custom pages. That will bring Canvas further into the realm of a content management systems than it currently is, but I am very open to moving that direction if it will improve the users' experience.

**Comment by soywod** [comment]
Hey, it has been a while :)
Glad to see that Canvas grows up ! What's up on this suggestion ?

I like your idea, @Vviizard. this will bring up Canvas to a real CMS. Keep in the UX you have now will be a real challenge :/

**Comment by Vviizard** [comment]
@soywod I've been occupied by other projects recently, but I might have time to look at it over the holidays.

**Comment by glennmcewan** [comment]
Adding custom pages is currently already _quite_ simple, if you know how to do that in Laravel. Add a new route, new controller, and a Blade file.

However, having a core Contact form would be excellent. I'd be happy to contribute something towards that if anybody has suggestions. I'd like to include a contact form on my own instance.

As for Impressum, that _may_ make sense to be bundled with core...it's quite a simple and straight-forward page which could be enabled via the Settings panel and managed fully within the CMS -- and it shouldn't add much bulk.

**Comment by austintoddj** [comment]
Anything you want to contribute @glennmcewan is always welcome!
