### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#143]
**Designers Wanted!**

Canvas has been _evolving quickly_, and it is very different [today](https://github.com/austintoddj/canvas/releases/tag/v2.1.5) than when it [first released](https://github.com/austintoddj/canvas/releases/tag/v1.0). One of the newest enhancements to the application was the modularity (if that's a word) of the resources. A theme directory is located at `resources/assets/sass/theme/` for you to apply any style modifications you'd like to make to your blog. If you choose to upgrade Canvas to the latest version, all you'd need to do is export your data archive and grab your child theme directory and apply them to your new installation. Pretty easy!

I think having some pre-composed themes would enhance the draw for newcomers to Canvas. These themes can be as bold or minimal as you want. Everyone has such a different taste. So, if you'd like to create a standalone child theme for the front-facing blog, go ahead and send me the `styles.scss` file and I'll create a new repository for all Canvas themes, giving you the credit for your contribution of course. Can't wait to see your creativity on this one!

**Comment by Bobeta** [comment]
Great idea, I'll try to find some time and make a theme. 👍  Where do you want us to send/publish the theme files?

**Comment by austintoddj** [comment]
@Bobeta Thanks! Can't wait to see what you come up with. If you just merge your proposed theme into [Palette](https://github.com/austintoddj/palette) in the same fashion as the `helios` theme, I can add it in immediately. Let me know if you have any more questions!

**Comment by Bobeta** [comment]
@austintoddj I finally got some time to look into this. The current theming structure allows for only CSS/SASS styling. I would like to change some of the default html for more flexibility regarding the layout. How would you suggest I create a solution with some custom html? Should I create separate blade files that override the default ones or something else?

**Comment by austintoddj** [comment]
@Bobeta Yes, that's the downside of the current theme setup. If you want to go ahead and try to create separate blade files like you mentioned that can override the default setup and somehow keep it all compact enough to where we can still swap themes in and out, I'd love to see it. 

**Bonus Points:** Think of a way we can display the title from the backend admin section of the app of what theme we are currently running, i.e. Default theme, Helios Theme ...

**Comment by reliq** [comment]
I'll take a jab at this @austintoddj!

**Comment by Bobeta** [comment]
@austintoddj I figured. I think we should together think out a more abstract strategy, perhaps use some of the same concepts as the plugin creation with hooks etc.

**Comment by reliq** [comment]
With the core extracted in a separate package (austintoddj/easel#2) we can look into the possibility of creating canvas themes as laravel packages, say for example _vendor/canvas-theme-x_. 

This would allow themes to also be able to export/replace views (resources/views/vendor/canvas), solving @Bobeta's issue.

Reverting to the default set of views would be a matter of installing the canvas default theme (e.g. _vendor/canvas-theme-default_). 

@austintoddj if we had an organization page though; we could then better organize these _default_ packages (core, default themes, etc).

Thoughts?

**Comment by Bobeta** [comment]
@austintoddj could you get back regarding the suggestion from @reliq ?

**Comment by austintoddj** [comment]
@Bobeta The project is currently undergoing it's transformation from 1 repo to 2, and [CNVS](https://github.com/cnvs) has been created to house the whole ecosystem. Once we have the project back to where it was before, with a couple important improvements, we will begin looking at this. I agree with the suggestion @reliq made here though, and now we've opened up the opportunity to use this type of logic now that the project is transforming.

**Comment by Bobeta** [comment]
Sounds amazing and the transformation looks very promising, keep it up! How does the roadmap look now and which timeframe are we walking about (aprox)?

**Comment by austintoddj** [comment]
@Bobeta If all goes well, we are likely looking at a major release next week. 🎉

**Comment by Bobeta** [comment]
@austintoddj Awesome! 👍 I'm really excited to experience it!

**Comment by Bobeta** [comment]
@austintoddj Is it going well, any release date yet? Just tell me if you guys need any assistance! 😄

**Comment by austintoddj** [comment]
@Bobeta Yes! Everything is going very smoothly, the contributing devs are putting in some hard work getting this all prepped for release. Since this week is 🎄 Christmas, the release is going to be pushing back a little further than what I previously expected. I'm looking more at a January 2017 window, since that will give everyone enough time to take care of their own lives first, which is paramount 😉 Thanks for checking in though and keep your eye out for more updates!
