### ISSUE TITLE
Tag creation and management

### ISSUE THREAD

**Issue by cconover** [cnvs/canvas#214]
Creating and managing tags can feel a little cumbersome, particularly with all of the required fields for each tag. Is it possible to set fields as optional, or is that hard-coded? It would also be nice to be able to create tags on-the-fly when writing a post. Are there any options somewhere to tweak the behavior of the tag system?

**Comment by austintoddj** [comment]
@cconover That's not a bad idea. Let me look into it and see what I can find, I'll get back to you with more info on it.

**Comment by austintoddj** [comment]
This could be something we look into implementing in the future.
