### ISSUE TITLE
[POLL] Canvas Organization Name

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#267]
Canvas will soon be moved to live under an Organization on GitHub going forward. Which of these names best suits the build?

* cnvs
* gluve

**Comment by Jeroen-G** [comment]
What is gluve?
Why not canvas?

**Comment by austintoddj** [comment]
@Jeroen-G I should have prefaced it. 

canvas, canvascms are already taken. 

Origin of `gluve`:
So I thought about the glue used in making a canvas.
Then I thought of groove.
And then...  Gluve!

**Comment by Jeroen-G** [comment]
Painter, pictor as the person drawing on the canvas
Linen, cotton as the material canvas is made from.

**Comment by Naoray** [comment]
What about Laravas, Laracan...

...something related to the framework?

**Comment by austintoddj** [comment]
Thanks everyone for your participation. You'll see the results shortly.
