### ISSUE TITLE
Adding backend pages

### ISSUE THREAD

**Issue by Jeroen-G** [cnvs/canvas#270]
If I want to add pages (CRUD) to the backend, what would be the best way to do so?

**Comment by austintoddj** [comment]
Adding them from the site UI? Or going into Laravel and manually adding everything?

**Comment by Jeroen-G** [comment]
Hardcoding in Laravel is fine. :)

**Comment by austintoddj** [comment]
@Jeroen-G Sorry I've been late in getting back to you. Canvas is still undergoing it's transformation into [2 repositories](https://github.com/cnvs).

Right now, it's not a built in feature in Canvas to add more pages, but if you have a running instance of Canvas all you'd need to do is follow the default Laravel way of adding pages:

- Register a route in `routes/web.php`
- Create a `show()` method in a controller
- Create a corresponding view in `resources/views/`

**Comment by Jeroen-G** [comment]
Ah ok. I was wondering if there were some magic to it, since as you say the stuff is separated into two repositories.

I didn't think you were late btw.

**Comment by austintoddj** [comment]
Nope not really any magic about it.

**Comment by austintoddj** [comment]
If this is sufficient for you @Jeroen-G, would you mind closing this out? 👍
