### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#272]
On the `develop` branch, when you run:

```
composer dump-autoload
```

you are presented with some warnings. Not fatal, but wonder if we can address them.

<img width="1274" alt="screen shot 2016-12-03 at 9 07 53 am" src="https://cloud.githubusercontent.com/assets/8037011/20860223/9fa0ec80-b938-11e6-8dbf-6f9185b8eff3.png">

**Comment by Jeroen-G** [comment]
Are the migration files published to the user's directory from the core package? Because Laravel seems to try to run both.

**Comment by reliq** [comment]
@Jeroen-G has a point. This happens when migration files are published.

 _artisan_ only uses the published migrations. Composer, however, will complain as it _autoloads_ both `database` directories. 

So it's _safe_ to ignore these warnings.

**Comment by austintoddj** [comment]
Ok. Thanks for the heads up.
