### ISSUE TITLE
Version number is wrong

### ISSUE THREAD

**Issue by Zaghyr** [cnvs/canvas#273]
Hi,

I just installed canvas by `composer create-project cnvs/canvas`

Composer diplays : `Installing cnvs/canvas (v2.2.0)`

It is the latest version in packagist.

But when i am login in admin panel, we can see "Canvas v2.2.0 is available! Please update now.".

When i check in MySQL database, in **settings**, 
"canvas_version : v2.1.17", 
"latest_release: v2.2.0"

I think you did not updated the version in `config/blog`

Thanks !

**Comment by austintoddj** [comment]
Right now, Canvas is in the process of transforming into 2 separate repositories, so an issue like this falls under what is to be expected during this process. Apologies for the issue, but it will be resolved in the next available release.
