### ISSUE TITLE
Maintenance Mode does not work

### ISSUE THREAD

**Issue by Zaghyr** [cnvs/canvas#274]
Hi,

When i click in "ENABLE MAINTENANCE MODE" in Tools menu, i don't have "a 503 - Be Back Soon page" !

Thanks !

**Comment by austintoddj** [comment]
This is because you are the admin of the site. As the user who initiated the maintenance mode, your IP is whitelisted to still have full access to the blog.

Try this:

Use another browser window in incognito/private mode, and try to access the blog. You should be presented with the 503 page now.
