### ISSUE TITLE
Images not visible / Add Symbolic Link for media manager

### ISSUE THREAD

**Issue by mabd91** [cnvs/canvas#275]
Add a step to installation script to create symbolic link to /storage/app/public inside /public 

```
#You can run this command to do just that for Laravel 5.3
php artisan storage:link
```

**Comment by austintoddj** [comment]
Right now, Canvas is in the process of transforming into 2 separate repositories, so an issue like this falls under what is to be expected during this process. Apologies for the issue, but it will be resolved in the next available release.
