### ISSUE TITLE
Theme installation

### ISSUE THREAD

**Issue by donmbelembe** [cnvs/canvas#278]
I'm trying to install the theme from https://github.com/cnvs/palette 
following the instruction, after running the gulp cmd everything works fine but the theme is not changing

here is the theme  **https://github.com/cnvs/palette/tree/master/modern-blue/styles.scss**

and i'm copying it to the directory **C:\wamp\www\projects\canvas\vendor\cnvs\easel\resources\assets\sass\theme**

is it the right directory to set the theme style ?

**Comment by austintoddj** [comment]
Right now, Canvas is in the process of transforming into 2 separate repositories, so an issue like this falls under what is to be expected during this process. Apologies for the issue, but it will be resolved in the next available release.
