### ISSUE TITLE
Testing a specific branch of Easel

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#281]
When testing the `feature/scout` branch of Easel, I would assume the `composer.json` file here in Canvas simply needs to have this as its updated `require` block:

```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/cnvs/easel"
        }
    ],
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "cnvs/easel": "dev-feature/scout",
        "doctrine/dbal": "^2.5"
    },
```

This will however only throw this problem:
![screen shot 2016-12-21 at 2 41 28 pm](https://cloud.githubusercontent.com/assets/8037011/21405443/9b4f8540-c78b-11e6-8345-60af86c6a019.png)

Thoughts on this @reliq?

**Comment by reliq** [comment]
@austintoddj you would need to change the minimum stability block in canvas' `composer.json`:

`"minimum-stability": "beta"` --> `"minimum-stability": "dev"`
