### ISSUE TITLE
Cannot get project to install with sqlite

### ISSUE THREAD

**Issue by LeAcid** [cnvs/canvas#282]
I have tried a few different times. But when I am trying to install canvas using sqlite I get a no such table: posts error. Is this something that is to be expected and should I just go with another db?
![error](https://cloud.githubusercontent.com/assets/13734458/21524840/76dad1ce-ccd6-11e6-8fac-321d3b6361ac.png)

**Comment by austintoddj** [comment]
@LeAcid Right now, Canvas is in the process of transforming into 2 separate repositories, so an issue like this falls under what is to be expected during this process. Apologies for the issue, but it will be resolved in the next available release.

**Comment by LeAcid** [comment]
So I just realized what the problem is, I was going to suggest an edit to the installation page if that is ok. I did not realize there was an artisan command to complete the installation and it is not listed on the docs

**Comment by austintoddj** [comment]
When the next release goes out, the installation steps will be found in the [Official Documentation](https://cnvs.readme.io/docs).

**Comment by LeAcid** [comment]
Is this something that I will be able to upgrade when the next release comes out? Or should people be waiting for the next release? Also is there any way for me to get involved in this project at this time? I love what I'm seeing so far

**Comment by newpain01** [comment]
There are no migrations in the repo as I can see. I really like the project, but I can't find a way to install it right now, and I need a blog application in the next few days. Is there any way I can install it? I am also interested in contributing in any way I can. Please let me know.

**Comment by LeAcid** [comment]
I was able to install it with the artisan command - php artisan canvas:install

**Comment by newpain01** [comment]
@LeAcid Thanks a lot, I didn't even know about that command. Installed it successfully now.

**Comment by austintoddj** [comment]
@newpain01 Sorry for the delay. Hoping for a release this week. Are you able to use Canvas till then or has it broken for you?

**Comment by newpain01** [comment]
@austintoddj Thanks for your reply. I was able to install it with some small changes, it's working now.
If I can contribute in any way, please let me know.

**Comment by austintoddj** [comment]
@LeAcid @newpain01, the latest release is out and should solve this issue. Feel free to close it out when you see it work! 👍

**Comment by LeAcid** [comment]
@austintoddj Works like a charm!
