### ISSUE TITLE
Categorized posts

### ISSUE THREAD

**Issue by serrexlabs** [cnvs/canvas#289]
Is there anyway to categorize posts ?

**Comment by austintoddj** [comment]
@serrexlabs At this time, you can only tag posts. From the frontend, you can click on a tag and get all the associated posts, but that's the extent of categorization.

**Comment by serrexlabs** [comment]
Anyway I'm gonna implement category  in my project. I will make a pull request to easel repo. If you need it.

**Comment by austintoddj** [comment]
@serrexlabs Yes go ahead and send a PR over to Easel and I'll look it over.

**Comment by serrexlabs** [comment]
@austintoddj sure, will do
