### ISSUE TITLE
Getting error in php artisan

### ISSUE THREAD

**Issue by cleopatra27** [cnvs/canvas#291]
PHP Warning: require(C:\xampp\htdocs\can failed to open stream: No such file or di trap\autoload.php on line 17 Warning: require(C:\xampp\htdocs\canvas\b d to open stream: No such file or directo autoload.php on line 17 PHP Fatal error: require(): Failed openi tstrap/../vendor/autoload.php' (include_p docs\canvas\bootstrap\autoload.php on lin Fatal error: require(): Failed opening re p/../vendor/autoload.php' (include_path=' canvas\bootstrap\autoload.php on line 17

**Comment by ruchern** [comment]
Try `composer dumpautoload` see if it works?

**Comment by austintoddj** [comment]
Thanks for the help @ruchern. Did this fix your issue @cleopatra27?

**Comment by ecnerret-adajet** [comment]
I got the same error. I tried the `composer dump-autoload` but gives me this error
`Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\canvasblog\bootstrap\app.php:14
Stack trace:
#0 C:\xampp\htdocs\canvasblog\artisan(18): require_once()
#1 {main}
  thrown in C:\xampp\htdocs\canvasblog\bootstrap\app.php on line 14`

Thanks..

**Comment by austintoddj** [comment]
Do either of the solutions [here](https://laracasts.com/discuss/channels/general-discussion/fatal-error-class-illuminatefoundationapplication-not-found-in-pathtoprojectbootstrapappphp-on-line-14?page=1) or [here](https://github.com/jenssegers/laravel-mongodb/issues/944) give you different results in your particular installation?

**Comment by LittleHans8** [comment]
@cleopatra27 ,@ecnerret-adajet 
Re cloning the repo,and try to run `composer install` or `composer update`

**Comment by ruchern** [comment]
Check your permissions. The easiest way is to run `chmod 777 -R bootstrap/` (This is not recommended, but is the easiest way to check for permissions.

**Comment by austintoddj** [comment]
@cleopatra27 Good to hear. So the problem has been resolved?
