### ISSUE TITLE
building off canvas

### ISSUE THREAD

**Issue by iiCe89** [cnvs/canvas#292]
Hey i want to use Canvas is it possible to create a new Homepage off it etc and allow user to navigate to blog from that ? as apposed to using just as standalone blog

**Comment by reliq** [comment]
Building a site around canvas is possible since the core of canvas is simply a Laravel package. You can add your own controllers, views, models, routes, etc. as if it were a regular install of Laravel 5.3.

**Comment by austintoddj** [comment]
Does that answer your question @iiCe89? Feel free to close this out if it does.

**Comment by iiCe89** [comment]
Yes thank you guys
