### ISSUE TITLE
Method Spoofing for Newer HTTP Verbs (in AJAX)

### ISSUE THREAD

**Issue by awjudd** [cnvs/canvas#293]
The server that I use has an issue where I don't receive requests for the newer HTTP verbs (i.e. PUT).  This is immediately apparent when trying to edit a blog post.  I hit the "update" button and then it underlines the slug and says "Whoops, something went wrong".

I've noticed that the rest of the site uses method spoofing (built into Laravel) I was wondering if it can also do that for AJAX?  That would make the application more consistent in the requests, and make it work on my system.

Please let me know if you need more information.

**Comment by austintoddj** [comment]
@awjudd Could you post the system information from the Settings page in the blog admin? 

I'll look into what it would take to make a request like this happen.

**Comment by awjudd** [comment]
System Information: https://gist.github.com/anonymous/f45c0df77e12d4c0d125cc47731b9be1

**Comment by awjudd** [comment]
Looking through the code, it doesn't look like you are using VueJs / Vue-Resource.  If you were, I used the following interceptor to get around this issue.

Maybe something similar can be used for your code?

```js
Vue.http.interceptors.push((request, next) => {

    // modify request
    if(request.method != 'POST') {
        request.params._method = request.method;
        request.method = 'POST';
    }

    next();
});
```

**Comment by austintoddj** [comment]
@talvbansal Any thoughts on this?
