### ISSUE TITLE
ErrorException in helpers.php line 411:

### ISSUE THREAD

**Issue by iiCe89** [cnvs/canvas#294]
Set up new install as instructions and get this when viewing on site

File vendor/canvas/assets/css/frontend.css not defined in asset manifest. (View: C:\Users\vinnd\Code\laser\vendor\cnvs\easel\resources\views\frontend\partials\css.blade.php) (View: C:\Users\vinnd\Code\laser\vendor\cnvs\easel\resources\views\frontend\partials\css.blade.php) (View: C:\Users\vinnd\Code\laser\vendor\cnvs\easel\resources\views\frontend\partials\css.blade.php)

**Comment by austintoddj** [comment]
@iiCe89 If you install a fresh Canvas application but do not have a clean database that you're starting from scratch with, you'll see this error. Did you already have a database that you'd run the initial installation with on a different install?

**Comment by iiCe89** [comment]
could be i did create new sqlite DB and ran php artisan migrate

**Comment by austintoddj** [comment]
Ok. Would you try one more time, a fresh install with a clean database and see if that works for you?

**Comment by iiCe89** [comment]
seems to have resolved issue when i ran  php artisan canvas:update i now see page but its only allowing me to login

**Comment by austintoddj** [comment]
Hm, sounds like perhaps some of the views didn't propagate during the update or something like that. So that's what happened during an update, what about a fresh install?

**Comment by iiCe89** [comment]
yup now trying :)

**Comment by iiCe89** [comment]
Tried again fresh install create sqlite DB and was hit with the same message as above and this

![screenshot](https://cloud.githubusercontent.com/assets/19858208/21768661/bf09545c-d672-11e6-9c7c-2fb396f5ea04.png)

**Comment by austintoddj** [comment]
Ok, thanks for running that test. I'll look into this further and see what I can find out.

**Comment by iiCe89** [comment]
ok thank you the database/sqlite is currently storing in the Storage folder it was originally stored in database folder but just gave me error saying it could not find database sqlite in storage folder so tried that method which then gives the above message after running canvas/update it gives me that page in browser hope that information helps

**Comment by sebbaum** [comment]
Concerning the initial problem in this thread. I had the same problem. 
After running `php artisan canvas:install` and following the installation process, everything seems to work.
Unfortunately the official documentation is not mentioning that running `php artisan canvas:install` is required.

**Comment by austintoddj** [comment]
@sebbaum In the installation process, you are directed to access a web browser after brining in the project where you'll see this screen:

![canvas-welcome](https://cloud.githubusercontent.com/assets/8037011/21955227/194f1340-da2c-11e6-98c5-020961a492c8.png)

I assumed that this would be clear enough for people to follow and have a nice Welcome page to land on as they see the project for the first time. In your opinion it's simply better to keep that in the documentation?

**Comment by austintoddj** [comment]
@sebbaum The official docs have been updated and provide a bit more clarity. 👍 

https://cnvs.readme.io/docs
