### ISSUE TITLE
Permissions errors while changing theme

### ISSUE THREAD

**Issue by trahma** [cnvs/canvas#295]
While trying to change the theme on a base install yields the error

> ErrorException in Filesystem.php line 204:
copy(/var/www/public/vendor/canvas/build/assets/css/frontend-302c0069fb.css): failed to open stream: Permission denied

I've followed the directions for a base install at https://cnvs.readme.io/docs.  There were no directions listed for adjusting permissions on ./storage or public/vendor/canvas/build.  

Perhaps I missed something, I feel like this should have been documented though.

**Comment by austintoddj** [comment]
@trahma Could you try running the following command from a terminal in the project root? If that works for you, I'll go ahead and include it in the docs.

```
sudo chmod -R 777 storage/
```

Per [Laravel's installation](https://laravel.com/docs/5.3), you need to alter permissions to the `storage` directory.

**Comment by trahma** [comment]
That was the first fix, the second fix was that I had to give write permissions to public/vendor for the webserver.

**Comment by austintoddj** [comment]
Ok. Thanks for running that test. Would you be able to briefly document those changes you ran and send them to me at austin.todd.j@gmail.com? I'll look them over and then get them in the docs as soon as possible.

**Comment by austintoddj** [comment]
@reliq Just ran into this same issue, here's the output of the error:

![screen shot 2017-01-10 at 8 36 15 am](https://cloud.githubusercontent.com/assets/8037011/21811570/c57edd72-d715-11e6-9e3f-fbb25d8bb8dc.png)

Issue was resolved by doing what @trahma stated above, changing permissions of the `public/vendor` directory. Do you think it's something we need to add into the install documentation?

**Comment by trahma** [comment]
Sorry haven't had a chance to send the email will do so later today.  The easiest way to resolve this issue is to set 777 however for some users that may not be the safest solution.  Out of the laravel docs:

> Directory Permissions
After installing Laravel, you may need to configure some permissions. Directories within the  storage and the bootstrap/cache directories should be writable by your web server or Laravel will not run. If you are using the Homestead virtual machine, these permissions should already be set.

**Comment by ChristianYeah** [comment]
Actuallly, change the owner of dict to apache or nginx will be fine. Quite simple

**Comment by LittleHans8** [comment]
It seems the same error when I try to change my blog setting(path:/admin/settings) 
**Although it output error,I refreshed the page,and it has been saved successfully** 

> ErrorException in Filesystem.php line 204:
copy(/var/www/html/blog/public/vendor/canvas/build/rev-manifest.json): failed to open stream: Permission denied

> CANVAS_VERSION:             v3.0.5
   PHP_VERSION:                7.0.13-0ubuntu0.16.04.1
   DATABASE_CONNECTION:        MYSQL
  WEB_SERVER:                 nginx/1.10.0

**Comment by austintoddj** [comment]
Fixed in [v3.1.1](https://github.com/cnvs/easel/releases/tag/v3.1.1)

**Comment by sevmardi** [comment]
I am still somehow experiencing this. 
v3.4.2 is installed. 

Any ideas?

**Comment by jringeisen** [comment]
@sevmardi same here, I'm on version 3.4.3. Anytime I hit save in the settings I get this error:

`copy(/home/forge/ringocodes.com/public/vendor/canvas/assets/js/vendor.js): failed to open stream: Permission denied`
