### ISSUE TITLE
Error in new install

### ISSUE THREAD

**Issue by eduardor2k** [cnvs/canvas#297]
I've just setup a new install of canvas but i keep getting this error:

File vendor/canvas/assets/css/frontend.css not defined in asset manifest. (View: /var/www/xxx/vendor/cnvs/easel/resources/views/frontend/partials/css.blade.php) (View: /var/www/xxx/vendor/cnvs/easel/resources/views/frontend/partials/css.blade.php) (View: /var/www/xxx/vendor/cnvs/easel/resources/views/frontend/partials/css.blade.php)

**Comment by austintoddj** [comment]
@eduardor2k This error can pop up when you install Canvas with an *already existing database*, one that has been used to run an installation before.

So, go ahead and try creating a fresh database, and try the installation again. Let me know if you see the same error.

**Comment by eduardor2k** [comment]
Thanks, it was exactly that!

I had executed manually "php artisan migrate".

rookie mistake

Thanks a lot!
