### ISSUE TITLE
Title Field Sanitization Broken

### ISSUE THREAD

**Issue by dlopez** [cnvs/canvas#298]
When using a double quote in the title field. It breaks the form input.

![image](https://cloud.githubusercontent.com/assets/167449/21997184/e27414de-dbfb-11e6-9305-facf19c38b33.png)

**Comment by ChristianYeah** [comment]
edit vendor\cnvs\easel\resources\views\backend\post\partials\form.blade.php line 41
using '' instead of "" for value attr will work.
but its a temperal fix

**Comment by austintoddj** [comment]
Fixed with https://github.com/cnvs/easel/commit/456e2458fb0bf4cb0ad89749c4120adf20c95741
