### ISSUE TITLE
Route [home] not defined

### ISSUE THREAD

**Issue by jwhulette** [cnvs/canvas#301]
I want to have the blog as a path on my site. So I have /blog set in the config to 'blog_path' => '/blog', if I set 'blog_prefix' => '/', I get the following error.
**Route [home] not defined. (View: /vagrant/vendor/cnvs/easel/resources/views/backend/home/sections/welcome.blade.php)** 
when trying to access the admin screen.
If I add sort a prefix it works.

**Comment by austintoddj** [comment]
@reliq This is still a WIP correct?

**Comment by reliq** [comment]
@austintoddj yes. @jwhulette you will have issues with integration until the next minor release.

**Comment by austintoddj** [comment]
@jwhulette `v3.1.1` is out now. Let me know if that cleared your issue up.
