### ISSUE TITLE
Unable to activate theme

### ISSUE THREAD

**Issue by jwhulette** [cnvs/canvas#303]
I am unable to active my custom theme. I cloned the Paper dark theme and just change the name and title. I added the theme to my composer file and ran update. The theme does not show on the admin panel as a selection.

**Comment by austintoddj** [comment]
@jwhulette You can find out more about custom theming in the [official documentation](https://cnvs.readme.io/docs/theme-development).

**Comment by jwhulette** [comment]
I followed the documentation. The theme shows in my installed.json file but the admin interface never displays it. From my reading of the code, it should parse the installed.json file to display any themes. Is there a cache somewhere I need to clear. I have done composer dumpauotload, cache:clear, view:clear & optimize.

**Comment by austintoddj** [comment]
Thoughts on this @reliq?

**Comment by jwhulette** [comment]
Sorry, but it's been a long day. It was a vagrant issue. My local copy was not being synced. A vagrant restart resolved the issue.
