### ISSUE TITLE
easel checks the existence of tables every time even after the installation

### ISSUE THREAD

**Issue by ChristianYeah** [cnvs/canvas#304]
I was working on the cache for the easel, and realised that the framework checks the existence of table every time.

I think an install.lock file would be more appropriate.

I commented all unnecessary code in ``SetupHelper`` personally

**Comment by austintoddj** [comment]
@ChristianYeah What do you mean it checks for the existence of a table every time? The `requiredTablesExists()` method is meant to check for existing tables on a fresh installation, and then it's unused throughout the rest of the application. What code did you comment out in `SetupHelper.php`?

**Comment by ChristianYeah** [comment]
@austintoddj problem is, it still work after the installation. Can you double check it again? or only I have this problem
<img width="1212" alt="screen shot 2017-01-21 at 12 39 43 am" src="https://cloud.githubusercontent.com/assets/7412085/22152343/51762416-df72-11e6-9d17-b5d93e9133b0.png">

**Comment by reliq** [comment]
@ChristianYeah this should resolve your issue: https://github.com/cnvs/easel/commit/f9ff298b4feed4eadd45435712d5596777df8430
