### ISSUE TITLE
Users can view and edit their own post only in the dashboard

### ISSUE THREAD

**Issue by jestintab** [cnvs/canvas#305]
I want the users can edit their own posts only, so I added the below code in the PostController 
```
namespace Canvas\Http\Controllers\Backend;

use Session;
use Canvas\Models\Post;
use Canvas\Jobs\PostFormFields;
use Canvas\Http\Controllers\Controller;
use Canvas\Http\Requests\PostCreateRequest;
use Canvas\Http\Requests\PostUpdateRequest;
use Auth;
use Canvas\Models\User;

class PostController extends Controller
{
    /**
     * Display a listing of the posts.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {   
        if ( User::isAdmin(Auth::user()->role)){
            $data = Post::all();
        }else{
             $user = Auth::id();   
             $data = Post::all()->where('user_id', $user);
           
        }
       


        return view('canvas::backend.post.index', compact('data'));
    }
`
```

I don't know about the coding standard. That's why I posted here.

**Comment by austintoddj** [comment]
@jestintab So you are asking if the functionality could exist to where an admin user can't see all the blog content?

**Comment by ruchern** [comment]
Hi, I've attempted to push the feature on the easel repo. @austintoddj I tried to contribute. Should there be any errors, please let me know!

**Comment by talvbansal** [comment]
To me this sounds like it should be configurable depending on the needs / wants of the blog owner?

**Comment by jestintab** [comment]
Yeah it should be configurable option from admin side or add 3rd level for users like moderator.

**Comment by austintoddj** [comment]
I'll take this into consideration, adding another level of admin users.
