### ISSUE TITLE
404 when updating post (fresh installation)

### ISSUE THREAD

**Issue by trizz** [cnvs/canvas#306]
When I've a fresh installation (doesn't matter if it is a clone from GitHub, or via Packagist) and I want to update a post, I receive a 404:

`jquery.min.js:4 PUT https://<my.domain>/admin/post/3 404 (Not Found)`

Running a `php artisan route:list --path=admin/post` returns a few lines, including this one:
`PUT|PATCH | admin/post/{post}      | admin.post.update`

I've tested in both Chrome and Safari on macOS.

**Comment by austintoddj** [comment]
@trizz What version of Canvas are you currently running?

**Comment by ruchern** [comment]
Can confirm the problem too.

**Comment by trizz** [comment]
@austintoddj I've tried it with `comsposer create project`, the latest release (v.3.0.5 with the tag `vdbal`), the v3.0.1 release and the master branch. All as a fresh install with a `php artisan install:canvas`. I'm running currently v2.1.17 with no problems.

**Comment by austintoddj** [comment]
@trizz Thanks for the info. So you're still hitting an error when updating a post then? Trying to replicate the issue on my end but haven't been able to yet.

**Comment by trizz** [comment]
Yes, but it is worth to mention that it is on the same host as the old Canvas installation. Haven't tried it on a 'fresh' host, perhaps I've some caching issues, but it seems strange to me that everything else works perfect.

**Comment by austintoddj** [comment]
Interesting. Thanks for getting back to me. Since I haven't been able to replicate it on any of my environments, I would assume it has something to do with a caching issue. Let me know if you see anything else come up! 👍

**Comment by austintoddj** [comment]
@trizz If everything here is working out for you now, feel free to close this issue.

**Comment by trizz** [comment]
@austintoddj I've just set up a new domain/host, so I can try it when I've time with a fresh installation, on another domain, etc. I'll let you know if it is solved or not.

**Comment by trizz** [comment]
A clean install, on a new domain, with a new DB and I've still the same problem. After a bit of poor mans debugging (adding `<?php var_dump(\Request::isMethod('get')); var_dump(\Request::isMethod('put')); ?>` to `404.blade.php`) returns `bool(true) bool(false)` so apparently my browser sends the request as a GET instead of a POST (mimicking a PUT or PATCH).

I've tried it on macOS Sierra with Chrome, Vivaldi and Safari; none of them are working. Adding and deleting a post works fine. Also, I've tried editing a tag, and it is updated without problems.

**Comment by austintoddj** [comment]
@trizz Could you post the system information from the Settings page in the blog admin? 

I believe this may be a duplicate issue of #293

**Comment by trizz** [comment]
[Sure](https://gist.github.com/trizz/d952251b089cbcd5a53ff38eabc803d2) 😄

**Comment by austintoddj** [comment]
@trizz Does the latest update `v3.2.0` solve this issue for you?

**Comment by trizz** [comment]
Unfortunately not :(

**Comment by austintoddj** [comment]
Fixed with [v3.4](https://github.com/cnvs/easel/releases/tag/v3.4.0)
