### ISSUE TITLE
Custom pages?

### ISSUE THREAD

**Issue by marktopper** [cnvs/canvas#307]
Are there any plans for making support for custom pages?

Like a "About" page?

**Comment by austintoddj** [comment]
@marktopper This has been brought up a couple times and seems to be of interest to people creating a blog with Canvas. There isn't any current development on this feature, but I believe that this could fall under the larger umbrella of #177 in the end. With a plugin system, we could add on more CMS-like components.

**Comment by marktopper** [comment]
@austintoddj, thanks for that reference. Seems like a perfect way to handle this. Once a plugin system is created I can create this plugin/component myself and contribute to this wonderful project.
