### ISSUE TITLE
update and meta description

### ISSUE THREAD

**Issue by dam62500** [cnvs/canvas#309]
Hi,

I don't know if I'm the only one who has this problem but i can't update my blog (3.0.5 to 3.1.1 ) and Google doesn't take well the meta description. ( It takes one of the setting, description blog ) 

Any ideas?

**Comment by austintoddj** [comment]
@dam62500 The [Official Upgrade Guide](https://cnvs.readme.io/docs/upgrade-guide) should contain everything you need to upgrade from `v3.0.5` to `v3.1.1`. What error are you receiving?

What is going on with the meta description that isn't working?

**Comment by dam62500** [comment]
I don't have the meta description of the article but that one of settings when i look on Google, i can see there are two meta description in canvas for google and it's the first one google take, this one in the settings of the blog.

**Comment by austintoddj** [comment]
Ok @dam62500 I'll take a look at the meta sections and see if there is something we can fix there.

**Comment by dam62500** [comment]
When i inspect, i see two meta descriptions. I think it's the probem.

**Comment by austintoddj** [comment]
Great thanks for that bit of info. If you care to send a PR over to the `develop` branch on [Easel](https://github.com/cnvs/easel), I'd be happy to merge that in.

**Comment by austintoddj** [comment]
@dam62500 This is currently fixed in the `develop` branch. Will be pushed live with the `v3.2.1` update.
