### ISSUE TITLE
Any plan for saving drafts automatically?

### ISSUE THREAD

**Issue by printempw** [cnvs/canvas#311]
To my surprise, I found that canvas won't save the draft for me automatically at a specified time interval when I am working on the article. It's unbelievable!

It also didn't notice me when I tried to close the page with un-saved modification. I think add a notice like [this](http://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes) would be great 👍

**Comment by austintoddj** [comment]
Thanks for bringing this up @printempw. We'll look at getting this integrated in a future release!
