### ISSUE TITLE
Usage of user profiles

### ISSUE THREAD

**Issue by ruchern** [cnvs/canvas#312]
Are there further developments for user profiles? At the moment the application can only edit own profile. Should there be ways to view other user profiles in the future?

**Comment by austintoddj** [comment]
@ruchern Do you mean from within the application itself or from an outside source?

**Comment by ruchern** [comment]
@austintoddj Within the application itself.

**Comment by austintoddj** [comment]
When there are multiple users in the system, an admin user can update/view the other profiles under the Users section. Are you not seeing that in your installation?

**Comment by ruchern** [comment]
@austintoddj I have that. What I meant is normal users looking at profiles of other users.

**Comment by austintoddj** [comment]
Didn't have any plan to allow `User` level users to view others, since they are the lowest level. We could look into adding more levels of users, capable of different things. But for now, no, there isn't any plan in place for seeing other user profiles if you aren't an admin.

**Comment by ruchern** [comment]
@austintoddj Okay thank you!
