### ISSUE TITLE
Application Events

### ISSUE THREAD

**Issue by davidianbonner** [cnvs/canvas#313]
Firstly, excellent work! Canvas is great.

We're looking to automate some things like tweeting and posting snippets to medium etc. Are there any plans to implement system events. For instance `PostCreated`, `PostUpdated`etc?

If not, would you be open to this as a contribution. We will be implementing it in a fork anyway to get up and running as soon as possible.

**Comment by austintoddj** [comment]
Really glad you like Canvas @dbonner1987! At this time I haven't looked into implementing such an event system, but would be more than happy to accept it as a PR if you wanted to push one.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
