### ISSUE TITLE
Localization for Canvas Paper theme

### ISSUE THREAD

**Issue by florinfratica** [cnvs/canvas#317]
Hi.

I am using Canvas for my blog and I have to say that I am really pleased with this platform and I appreciate the effort you guys put into developing and mantaining it.

I'm blogging in my native language (romanian) and I think there might be others doing this too so I think that it would be pretty nice to have Canvas Paper theme front-end use Laravel's localization feature. This way, whenever you update Canvas to a newer version you will only have to modify the localization files not the views (if new pieces of text appear in the views).

**Comment by talvbansal** [comment]
@florinfratica I've not worked with any localised sites before, if you have would you be able to submit a PR on the `cnvs/easel` repository with the changes necessary. I agree it'd be a great addition and I'd personally love to see how its done too!

**Comment by florinfratica** [comment]
@austintoddj, I will try to do it this weekend or next weekend, but only for the frontend.

**Comment by austintoddj** [comment]
Sounds good @floriangaerber! Looking forward to seeing what you come up with!
