### ISSUE TITLE
Images with spaces in the name aren't viewable

### ISSUE THREAD

**Issue by lferro9000** [cnvs/canvas#318]
When uploading a new image, if the image name has spaces, it won't get previewed (and probably will not show on the frontend).

**Comment by ibnujakaria** [comment]
do you use linux?

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
