### ISSUE TITLE
Removing post image and update generates error

### ISSUE THREAD

**Issue by lferro9000** [cnvs/canvas#320]
I will get back to this later with more details, but this is the gist of it:

When editing a post with an image, and removing the image (the one on the right side of the edit form), and then update the post one will get the base symfony error.

I will try to chase later the logs of what happened to add to this.

**Comment by austintoddj** [comment]
Sounds good @lferro9000, let me know what you find.

**Comment by lferro9000** [comment]
The issue was related with how i was firing the builtin php webserver.

I was using index.php as router, which requires the addition on top of a check to see if the file exists before trying to fireup the rest of the code.

Either removing the routing option when firing the builtin webserver or adding that extra code will make everything work just fine.

**Comment by austintoddj** [comment]
@lferro9000 Could you expand on your solution above? Was that just a single-case-only solution, or something you wanted to see built into the app?
