### ISSUE TITLE
Fesh install error 

### ISSUE THREAD

**Issue by joselara** [cnvs/canvas#321]
Failed to clone https://github.com/austintoddj/laravel-jsvalidation.git via https, ssh protocols, aborting.
  - https://github.com/austintoddj/laravel-jsvalidation.git
    Cloning into '/Users/jose/Code/joselara/vendor/austintoddj/laravel-jsvalidation'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/austintoddj/laravel-jsvalidation.git/'
  - git@github.com:austintoddj/laravel-jsvalidation.git
    Cloning into '/Users/jose/Code/joselara/vendor/austintoddj/laravel-jsvalidation'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by joselara** [comment]
Looks like jsvalidation doesn't exists anymore.

**Comment by austintoddj** [comment]
@joselara You are correct. Using `austintoddj/laravel-jsvalidation` was a temporary fix for an issue we were experiencing with integrating a third-party package. With the [latest release](https://github.com/cnvs/canvas/releases), we've moved on to a permanent solution.

Reference #285 for more info.
