### ISSUE TITLE
When installing with --no-dev, post-install/update commands will not work

### ISSUE THREAD

**Issue by lferro9000** [cnvs/canvas#322]
There is an hard dependency of the post update/install commands to faker library.

The problem is that library is only installed on dev mode.

The solution is either remove those commands dependency from faker library, or move the library from "require-dev" to "require".

**Comment by austintoddj** [comment]
Thanks for bringing this up @lferro9000. I'll take a look in a little while and check out your PR 👍

**Comment by austintoddj** [comment]
@lferro9000 Just fixed this with the above commit by sending it to the `develop` branch. Will be merged into the main project on the next release. Thanks again!
