### ISSUE TITLE
Doesn't work over SSL?

### ISSUE THREAD

**Issue by goodbytes-gb** [cnvs/canvas#325]
I enabled CloudFlare force SSL and could no longer login. I noticed Canvas is forcing HTTP at login (or maybe it's failing due to mixed content and the browser is forcing non-HTTPS) as a result the session is killed, the login page just reloads.

**Comment by austintoddj** [comment]
Thanks for catching that @goodbytes-gb. Had not run into that issue myself yet. Let me look into it and see what I can do to help you.

**Comment by kingsloi** [comment]
@goodbytes-gb, @austintoddj, I went live with a blog, and https works fine. I use Laravel Forge. @goodbytes-gb, make sure you have set up https correctly, and you've used 'https://' in your base url in you .env file (or config file). My 2c!

**Comment by goodbytes-gb** [comment]
@goodbytes-gb, @austintoddj yeah sorry guys looks like it was my fault. I installed the certificate in forge but never actually activated it, forgot to click the button. false alarm. apologies :)
