### ISSUE TITLE
Question: do you have an example on how to add plugins to canvas

### ISSUE THREAD

**Issue by SerjoA** [cnvs/canvas#326]
hi, do you have some kind of example on how to extend canvas even further
thank you for the work its awesome

**Comment by austintoddj** [comment]
Thank you @SerjoA for your kind comments on the project! I don't currently have any examples of plugins, it's been a work-in-progress between a couple developers here. Anything that you have to offer in that area would be a very welcome contribution!

**Comment by SerjoA** [comment]
thank you for your kind words, i can try and make a plugin in my spare time, just need some info like what folder to put the plugin, how to connect it to the system, do you have any specific  request in mind? also , you can redirect me to someone who is working with this system also and i can ask him some info  and then  make a plugin

**Comment by reliq** [comment]
Hello @SerjoA, 

There is a base extension class here: https://github.com/cnvs/easel/blob/master/src/Extensions/Extension.php which we adapted from Flarum (https://github.com/flarum/core). Themes are extensions so they therefore extend this base class.

**Comment by SerjoA** [comment]
thanks @reliq  ill look into it and hope to learn from it

**Comment by austintoddj** [comment]
@SerjoA If you're satisfied with the answer provided here, feel free to close the issue out 👍

**Comment by SerjoA** [comment]
yes thank you, i am using now caffinated modules for laravel, its awesome
