### ISSUE TITLE
auto social publishing

### ISSUE THREAD

**Issue by voipworld** [cnvs/canvas#327]
hi Canvas Team
would you implement auto publishing to social?
its a good feature provided by wp
i allready created my blog with canvas, pretty satisfied;)
thanks!

**Comment by austintoddj** [comment]
@voipworld Thanks for checking out Canvas! You're right, auto-publishing to social media is a great feature, and I'll see what I can do to get it into a future release for Canvas. If you want to take a stab at it and send a PR to [Easel](https://github.com/cnvs/easel), I'd love to review it and see if we can merge it in. 👍

**Comment by ruchern** [comment]
@austintoddj Do you prefer to write the code manually to use the API of lets say Facebook or to integrate Socialite into this application?
