### ISSUE TITLE
not able to run artisan canvas:install

### ISSUE THREAD

**Issue by DanielFurmanov** [cnvs/canvas#328]
Greetings!
_I came here from https://github.com/cnvs/easel , because that repository isnt active_

I am trying to install canvas on existing project
while running `artisan canvas:install` I have stumbled in 
```
Welcome to the Canvas Install Wizard! You'll be up and running in no time...

Could not link storage/app/public folder to public/storage:
✘ symlink(): No such file or directory

Please provide the following information. Don't worry, you can always change these settings later.

Step 1/6: Creating the admin user account

 Email:
 > vvv@bb.com

 Password:
 > 

 First name:
 > first

 Last name:
 > second


An unexpected error occurred. Installation could not continue.
✘ SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "display_name" violates not-null constraint
DETAIL:  Failing row contains (3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, vvv@bb.com, null, null, 2017-03-31 16:21:03, 2017-03-31 16:21:03, null, null, null). (SQL: insert into "canvas_users" ("email", "updated_at", "created_at") values (vvv@bb.com, 2017-03-31 16:21:03, 2017-03-31 16:21:03) returning "id")

```

because installation can not create a canvas user in `cnvs/easel/src/Console/Commands/CanvasCommand.php`  https://github.com/cnvs/easel/blob/master/src/Console/Commands/CanvasCommand.php#L166  because, well, because the user model has `display_name` property which is `not null`:
![not_null](http://dl3.joxi.net/drive/2017/03/31/0018/2806/1227510/10/5ac1ef14f7.jpg)

**So I have some questions:** 
1) Why there is even a `find` part in `createUser()`? Canvas uses its own users, so there could be no existing users in the table which is just was created, right?
2) Am I missing something or this is a big issue?

**Suggestion:**
just replace 
`        $user = User::firstOrCreate(['email' => $email]);
`
with 
`        $user = User::firstOrNew(['email' => $email]);
`
and all should be good.

My system data: php 7.1, PosgreSQL, Laravel 5.3

**Comment by austintoddj** [comment]
@DanielFurmanov Thanks for checking out Canvas! You're detailed description of what's going on and a suggested fix is *awesome*, thanks for taking the time to write up a very proper issue. 

If you'd like to submit a PR to Easel with your proposed change, I'd love to help merge it into the project.

**Comment by DanielFurmanov** [comment]
@austintoddj  Yes, I would like to submit a PR. I am currently trying to augment canvas to my company's project. So I would be glad to submit some fixes. Should I open a different issue for and different bugs found?

**Comment by DanielFurmanov** [comment]
@austintoddj I have created a PR: https://github.com/cnvs/easel/pull/117 (to `develop` branch)

I haven't change anything but the line I mentioned, but I think if command uses an existing user (assuming it really can happen) that would be strange to change his/her already existing data AND role. Is it a concern?

**Comment by austintoddj** [comment]
Thanks again for sending this PR over @DanielFurmanov, it is merged into the project now so I'll close this one out. 👍
