### ISSUE TITLE
The admin edit post breaks when enter this script in <pre> tag

### ISSUE THREAD

**Issue by rd4704** [cnvs/canvas#329]
Hi I am loving using Canvas so far, but encountered a problem recently when I entered the following script in a blog page:
```
!function(a){"use strict";var b=function(b,c,d){var g,e=a.document,f=e.createElement("link");if(c)g=c;else{var h=(e.body||e.getElementsByTagName("head")[0]).childNodes;g=h[h.length-1]}var i=e.styleSheets;f.rel="stylesheet",f.href=b,f.media="only x",g.parentNode.insertBefore(f,c?g:g.nextSibling);var j=function(a){for(var b=f.href,c=i.length;c--;)if(i[c].href===b)return a();setTimeout(function(){j(a)})};return f.onloadcssdefined=j,j(function(){f.media=d||"all"}),f};"undefined"!=typeof module?module.exports=b:a.loadCSS=b}("undefined"!=typeof global?global:this);
    loadCSS('{{ elixir('css/app.css') }}');
```

The edit post page became blank. When I view-source: the page I can see the content is there, so seems like some UI glitch.

**Comment by austintoddj** [comment]
Thanks for checking out Canvas @rd4704! I will look into this ASAP and see if I can find out what's wrong.

**Comment by mpandar** [comment]
Like this problem, when the editor of the following, "/admin/post/edit" will display a blank
`{{echo}}`

**Comment by jleonardolemos** [comment]
Im having the same problem when putting this code in editor:

```html
<form method="post" action="/contents">
<input name="_method" type="hidden" value="put">
<input name="_token" type="hidden" value="{{ csrf_token() }}">
<input name="home[description]" type="text" value="{{ isset($description) ? $description : null }}" required>
<button>Enviar</button>
</form>
```

The blog is great, im enjoing very much, congrats!!

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
