### ISSUE TITLE
SimpleMDE example not same as rendered version

### ISSUE THREAD

**Issue by yoramdelangen** [cnvs/canvas#332]
While writing a blog post I noticed if im using HTML in SimpleMDE and watch the preview it works fine. But when showing the saved version it will not parse whats between the HTML tags. 
Perhaps its missing documentation about the differents between rendering and the example view.

Example:
```
<div style="border: 2px solid red; padding: 5px;">

![example.png](/storage/example.png)

</div>
```
Preview shows:
![screen shot 2017-05-12 at 10 55 34](https://cloud.githubusercontent.com/assets/1531885/25990931/cfd58090-3701-11e7-8a4a-1a27b9b616e4.png)

But when preview on the site it shows this:
![screen shot 2017-05-12 at 10 56 19](https://cloud.githubusercontent.com/assets/1531885/25990940/dcf92ccc-3701-11e7-89e8-6bcace74e0a2.png)

Its a problem with Parsedown...

**Comment by austintoddj** [comment]
@yoramdelangen Thanks for checking out Canvas! I'll take a look at this issue as soon as I can and see if I can resolve it for you.

**Comment by davidangel** [comment]
@yoramdelangen – If you an a trailing `/` to the opening div tag, it seems to work as you expect.

```
<div style="border: 2px solid red; padding: 5px;" />

![example.png](/storage/example.png)

</div>
```

Not a super elegant solution, but it may get you on your way.

**Comment by austintoddj** [comment]
Thanks for the help @davidangel! Still haven't been able to get around to this one yet, so I appreciate the help in the meantime 👍
