### ISSUE TITLE
The "Date Published" from the "Create Post" will hide the post if the server timezone is backwards compared to the browser timezone

### ISSUE THREAD

**Issue by nicolasembleton** [cnvs/canvas#333]
Hi, just discovered Canvas and it's bloody amazing!! 

I've published a post today and realized something. My server is in LA time, but I'm in Vietnam. When I create a post, the Javascript in the browser will take my time VN-time, but then when I publish and watch the home, it won't appear because the published time is in the future for the backend. 

So, reproduction: 
* Set your server at a given timezone in the past (< GMT, for example Los Angeles)
* Set your own timezone in say Japan (well in the future compared to LA) 
* Create a post and observe that the "Published At" time is in your browser time
* Publish it and go to home

Observed result:
* The post will not show (because the backend thinks it's in the future)

Expected result:
* The post should show (because it's actually just been posted to be public).

Timezones are always a thing...

**Comment by austintoddj** [comment]
@nicolasembleton Thanks for checking out Canvas, and glad you like it! Thanks for bringing up this point, always helps when it's tested in different parts of the globe. I'll take a look and see what I can do to fix this.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
