### ISSUE TITLE
Media Manager Error, could not display the list of directories

### ISSUE THREAD

**Issue by ibnujakaria** [cnvs/canvas#337]
I installed canvas version 3.1, after the new version of canvas comes out, i updated it with ./artisan canvas:update.

I dont know it happens after I updated the canvas or not, but here what i got:

![](https://preview.ibb.co/mFrGtQ/Screenshot_from_2017_06_27_12_38_50.png)

**Comment by talvbansal** [comment]
Hi @ibnujakaria, there's a fix for this being tested at the moment its because of some changes to the https://github.com/talvbansal/media-manager component that I'm the author of. Once this PR https://github.com/cnvs/easel/pull/141 is merged it will fix the issue you're having

**Comment by austintoddj** [comment]
@ibnujakaria The release of `v3.4.1` should have taken care of this for you. Could you confirm and then close out this issue when you've seen it working? Thanks! 👍

**Comment by ibnujakaria** [comment]
@austintoddj Im sorry for the late response. I've been trying it out, and it works really well! Thank you guys! 😄
