### ISSUE TITLE
Your DEMO is not working

### ISSUE THREAD

**Issue by jodumont** [cnvs/canvas#338]
when I try to log in you demo 

https://demo.cnvs.io/admin

I receive this message : Whoops, looks like something went wrong.

**Comment by austintoddj** [comment]
@jodumont Thanks for bringing this up. I've found that the problem lies in the [Dark Theme](https://github.com/cnvs/paper-dark), some of it's code hasn't been updated to the latest framework changes. I'll take care of this tonight and you should see it up and running again ASAP.

**Comment by austintoddj** [comment]
@jodumont Everything should be back to normal with the release of [v1.0.5](https://github.com/cnvs/paper-dark/releases/tag/v1.0.5) of Paper Dark.
