### ISSUE TITLE
Add Google+ entry to "Social Networks" in the user profile.

### ISSUE THREAD

**Issue by unrivaledcreations** [cnvs/canvas#340]
**Feature Request:** Add Google+ entry to "Social Networks" in the user profile.

**Comment by austintoddj** [comment]
Good feature request. I'll get this added to the upcoming release.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
