### ISSUE TITLE
Method addQuery does not exist

### ISSUE THREAD

**Issue by kylesean** [cnvs/canvas#342]
```
protected function tagIndexData($tag)
{
        $tag = Tag::where('tag', $tag)->firstOrFail();

        $reverse_direction = (bool) $tag->reverse_direction;

        $posts = Post::where('published_at', '<=', Carbon::now())->whereHas('tags', function ($query) use ($tag) {
           $query->where('id', '=', $tag->id);
        })
            ->where('is_published', 1)
            ->orderBy('published_at', $reverse_direction ? 'asc' : 'desc')
            ->simplePaginate(config('blog.posts_per_page'));
        $posts->addQuery('tag', $tag->tag);
}
```
this code above work very well in laravel 5.3, but in 5.4, I got `Method addQuery dose not exist`  this error.I don't know why. Have you run into this problem in laravel 5.4? Hope to get your reply,thanks.

**Comment by austintoddj** [comment]
@kylesean Thanks for checking out Canvas! We're not actually supporting Laravel 5.4 yet, but it's in the pipeline to make the upgrade. 👍

**Comment by kylesean** [comment]
@austintoddj I got it. I used to upgrade to laravel 5.4 myself. The problem lies at `simplePaginate()` method, which return a model has the `addQuery` method in laravel 5.3, but in 5.4,the method is missing.that made feel puzzled.
haha,I'm looking forward to your upgrade!

**Comment by kylesean** [comment]
I know the reason for this problem. Becasue Laravel has changed the `addQuery` method to `protected` in version 5.4.

```
protected function addQuery($key, $value)

public function appends($key, $value = null)
````
So,use `appends()` instead of `addQuery()`. May help you. :)
