### ISSUE TITLE
Admin Browser (broken link) and related question

### ISSUE THREAD

**Issue by dqfan2012** [cnvs/canvas#343]
**Broken Link**

I think the wrong URL has been given for the admin browser on the Update Your Profile page. The route given is **http://yoursite.com/adminbrowser/index?path=** instead of **http://yoursite.com/admin/browser/index?path=**

**Comment by dqfan2012** [comment]
In the vendor.js file, I basically replaced every place that has

```
this.prefix + "browser/..."
```

with

```
this.prefix + "/browser/..."
```

And everything works fine now.

**Comment by austintoddj** [comment]
@dqfan2012 So to clarify, what link exactly is not working right now on the Update Profile page?

**Comment by dqfan2012** [comment]
When you click the button for uploading your resume. Look at the console log. It'll display the error.

**Comment by austintoddj** [comment]
Aha perfect. Thanks, that is something we can resolve shortly.

@talvbansal Since we utilize the Media Manager on the Update Profile page, could you make the update to support the latest release?

**Comment by talvbansal** [comment]
Hi all!

Sorry for the late reply - I've had a look into this and whilst there is another issue that's occurred in the latest update it seems to me that this part is fine?

I've just pushed up a new branch to the easel repo and am going to give it another look over tomorrow before submitting a PR.

Thanks

**Comment by talvbansal** [comment]
PR Submitted
