### ISSUE TITLE
Theme development tip

### ISSUE THREAD

**Issue by jeroenherczeg** [cnvs/canvas#344]
In my composer.json I added a local repository while developing a theme, which made it nicer to work with. Could be interesting to add in the documentation.

`    "repositories": [
        {
            "type": "path",
            "url": "../canvas-theme"
        }
    ],
    "require": {
        ...
        "jeroenherczeg/canvas-theme": "@dev"
    },`

**Comment by austintoddj** [comment]
Great thought @jeroenherczeg. Let me see what I can do 👍
