### ISSUE TITLE
Class 'JsValidator' not found In custom theme

### ISSUE THREAD

**Issue by jeroenherczeg** [cnvs/canvas#345]
I get an error Class 'JsValidator' not found in resources/views/vendor/canvas/backend/settings/index.blade.php after adding my custom theme (which I forked from https://github.com/cnvs/paper).

There is a line `{!! JsValidator::formRequest('Canvas\Http\Requests\SettingsUpdateRequest', '#settings') !!}` but when I browse the default layout blade file (vendor/cnvs/paper-dark/resources/views/backend/settings/index.blade.php) this is not included.

**Comment by austintoddj** [comment]
The JSValidator class was removed from the main project. If you look at the `resources/views` directory of [Easel](https://github.com/cnvs/easel), those are the updated views you'll want to use in your custom theme. Make sense?
