### ISSUE TITLE
Issue with media manager

### ISSUE THREAD

**Issue by achrafkh** [cnvs/canvas#347]
I can't quit exit media-manager using the X or close button (Fresh install)

**Comment by austintoddj** [comment]
Thanks for the bug report @achrafkh. I'll check into this and get it resolved for the next release.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
