### ISSUE TITLE
Error when migration database

### ISSUE THREAD

**Issue by whendytakashy** [cnvs/canvas#348]
Hi. 
I'm trying canvas ( [Integration With Existing Projects](https://cnvs.readme.io/docs/integrating-canvas-in-an-existing-project) ), when i'm migrate i have error message : 

`[Illuminate\Database\QueryException]                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQ  
  L: alter table `canvas_users` add unique `canvas_users_email_unique`(`email`)) `

trying with Laravel 5.4

thnks.

**Comment by austintoddj** [comment]
Thanks for checking out Canvas @whendytakashy! We're currently in the process for upgrading to Laravel 5.4, so stay tuned for when the next release drops. Then you should be able to run the app just fine!

**Comment by whendytakashy** [comment]
Okay, stay tuned for next release canvas.
Thank u
