### ISSUE TITLE
Laravel 5.4 - Unable to locate factory [default]

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#349]
Laravel Dusk is throwing this error...

```bash
Time: 47 ms, Memory: 6.00MB

There was 1 error:

1) Tests\Feature\Auth\AuthenticationTest::it_validates_the_login_form
InvalidArgumentException: Unable to locate factory with name [default] [Canvas\Models\User].

/Users/austintoddj/Sites/canvas/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:226
/Users/austintoddj/Sites/canvas/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php:122
/Users/austintoddj/Sites/canvas/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:232
/Users/austintoddj/Sites/canvas/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:163
/Users/austintoddj/Sites/canvas/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:128
/Users/austintoddj/Sites/canvas/tests/CreatesUser.php:24
```

...everytime I run it. Can't seem to find why the factories are not autoloading.

**Comment by talvbansal** [comment]
Ive been digging into this and it looks like the `CreatesUser` trait is loaded before the definitions for the model factories are when the application is being scaffold-ed in dusk. 

I did a lot of working writing a package at work recently that mimicked a similar behaviour to laravel model factories so luckily with that knowledge this was quite easy to follow through for me. 

Inspecting the definitions for factories that are loaded before the trait returns an empty array but if you comment out the `$this->user = factory(User::class)->create();` part the definitions are fully loaded.

Whilst the CreatesUser trait is used in a number of tests, its a pretty basic trait that imo can be replaced / got rid of to get the dusk tests passing.

I can assist working on this if you'd like, just thought id report back what i've found.

**Comment by austintoddj** [comment]
Thanks for the insight @talvbansal. That'd be super great if you wanted to send a fix to `feature/l5.4` branch that does what you think needs to happen. Once that's pushed up I can make the rest of the tests functional again.

**Comment by austintoddj** [comment]
Fixed by @talvbansal
