### ISSUE TITLE
No `slug` input in the `Quick Draft` block but the system still verifies it

### ISSUE THREAD

**Issue by JKChen** [cnvs/canvas#352]
When I save a post as draft in the `Quick Draft` block on the `HOME` page, Canvas displays the error message of "The slug field is required." , but the page does not have `slug` input at all. In fact, it is hidden.

- Remove the verification of the slug field.
or
- Remove the `hidden` class of the slug field.
or
- Remove all validation when  `Save Draft`.

**Comment by glennmcewan** [comment]
@JKChen I have just tested this on my local copy of Canvas @ v3.4.2. and it has worked successfully.

Could you please confirm:
- which version of Canvas you are using
- PHP version
- which fields you're filling in (with sample data)
- and anything else you think may help

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
