### ISSUE TITLE
Trying To Run "PHP ARTISAN SERVE" returns No Such File or Directory on line 17

### ISSUE THREAD

**Issue by Bitart** [cnvs/canvas#353]
Hi,

This is the error line returned on my terminal:

```
PHP Warning:  require(C:\Users\Xampoo\wwwroot\canvas\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\Xampoo\wwwroot\canvas\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\Users\Xampoo\wwwroot\canvas\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Users\Xampoo\wwwroot\canvas\bootstrap\autoload.php on line 17
```

Running Win10, 64. But the same happens on Linux too.

**Comment by ruchern** [comment]
Did you run `composer install`? Seems like the Laravel Framework was not downloaded.

**Comment by Bitart** [comment]
You are completly right. Shame on me! Is it possible upgrade to LL5.5?

**Comment by austintoddj** [comment]
@Bitart Currently we're in the process of upgrading the app to Laravel 5.4. So 5.5 is still a little ways out.

**Comment by Bitart** [comment]
Thank you!

**Comment by qamarabbas408** [comment]
run <pre>composer instal</pre>l command in the root directory of your project in cmd

**Comment by austintoddj** [comment]
@qamarabbas408 Is this a question related to #353?

**Comment by qamarabbas408** [comment]
yep

**Comment by austintoddj** [comment]
Just verifying, you're not using `php artisan serve` on the `cnvs/canvas` repo, correct?

This repo is a package that's pulled into a Laravel app, and a lot has changed since this issue was opened in 2017, like it not being a standalone app anymore.
