### ISSUE TITLE
The tntsearch error in 3.4

### ISSUE THREAD

**Issue by chuoke** [cnvs/canvas#354]
I successfully upgraded 3.4 from 3.3, but there is an exception on the page when I save user info.  

![canvas_blog_bug1](https://user-images.githubusercontent.com/17611457/30466919-b148d04e-9a13-11e7-8849-e46f356fd8c8.png)   

what should I do?

**Comment by talvbansal** [comment]
Hi this is likely just a permissions error.

If you check which user has permission to write to the *.index files within your projects storage folder and them make sure that the webserver has write permissions it should fix this problem.

On ubuntu servers this can be done with this command in your project root:

````bash
sudo chown storage/*.index www-data:www-data
````

Give that a go and see how you get on.

**Comment by austintoddj** [comment]
@chuoke Check out the official docs here: [Troubleshooting Issues](https://cnvs.readme.io/v3.3/docs/troubleshooting#section-database)
