### ISSUE TITLE
Fatal error: require(): Failed opening required 'D:\xampp\htdocs\canvas\bootstrap/../vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\canvas\bootstrap\autoload.php on line 17

### ISSUE THREAD

**Issue by rdtandel** [cnvs/canvas#355]
i'm new to laravel.please update asap

**Comment by talvbansal** [comment]
Hi!


Looks like the vendor/autoload.php file can’t be found.

Can you run composer install from the command line and see if that fixes your problem please.

Thanks

**Comment by rdtandel** [comment]
i've done composer update.
now its showing "Whoops, looks like something went wrong."

**Comment by talvbansal** [comment]
Can you please follow the installation guide on the official documentation it should get get you through all of the base issue to get you up and running

**Comment by ruchern** [comment]
@rdtandel `php artisan key:generate`

**Comment by rdtandel** [comment]
@ruchern thanks. worked.
but css,js not loaded.

**Comment by fajarharys99** [comment]
Fatal error: Unknown: Failed opening required 'D:\SchoolProject\school\server.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0

**Comment by TranDucQuynh** [comment]
fajarharys99: try the following on your cmd line:

php -S localhost:8888 -t public

Make sure the "-S" is capitalized. Hope this resolves your issue.

**Comment by noranyahia** [comment]
Fatal error: Unknown: Failed opening required 'C:\xampp\htdocs\laravel54\server.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0
<<<help>>>

**Comment by mca93** [comment]
@rdtandel TranDucQuynh
I had a same problem and your comment helped!

Thank you!

**Comment by folayodele168** [comment]
Hi all, I have this issue right now and I need an urgent help
 
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'C:\xampp\htdocs\CRC Website/server.php' (include_path='.;C:\php\pear') in Unknown on line 0

**Comment by emekambachu** [comment]
> 
> 
> Hi all, I have this issue right now and I need an urgent help
> 
> Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0
> 
> Fatal error: Unknown: Failed opening required 'C:\xampp\htdocs\CRC Website/server.php' (include_path='.;C:\php\pear') in Unknown on line 0
i have this issue too

**Comment by manish774** [comment]
> Hi all, I have this issue right now and I need an urgent help
> 
> Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0
> 
> Fatal error: Unknown: Failed opening required 'C:\xampp\htdocs\CRC Website/server.php' (include_path='.;C:\php\pear') in Unknown on line 0

having same issue.. kindly reply with solution

**Comment by Ziaurrahaman7** [comment]
i  was uninsstall my xamp  but now i install again but my larabel project not run now what i do plz

**Comment by chrismcligeyo** [comment]
@MaungC  thanks. worked

**Comment by Malika3** [comment]
PHP Warning:  require(C:\xampp\htdocs\Guid/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Guid\artisan on line 18

Warning: require(C:\xampp\htdocs\Guid/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Guid\artisan on line 18
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\Guid/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Guid\artisan on line 18

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\Guid/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Guid\artisan on line 18



plz help

**Comment by austintoddj** [comment]
There's been a number of major updates since this issue was opened. Let me know if you continue to have installation issues with the latest (4.*) version of the package.

**Comment by Malika3** [comment]
@austintoddj yes i still have this problem with the latest (4.*) version of the package.

**Comment by austintoddj** [comment]
Did you run composer install in the Laravel app?

**Comment by lcnguyen181000** [comment]
![loi](https://user-images.githubusercontent.com/45620014/71086783-4651ce00-21cd-11ea-8a7b-159cc0af5dd6.png) help me.

**Comment by ruchern** [comment]
@lcnguyen181000 remove `http://localhost/` from the path and see if it works.

**Comment by lcnguyen181000** [comment]
> @lcnguyen181000 remove `http://localhost/` from the path and see if it works.

![image](https://user-images.githubusercontent.com/45620014/71090384-7bfab500-21d5-11ea-92b8-805448e63812.png)
it still not woking :((

**Comment by Oluwatobilobaoke** [comment]
Always run composer install directly in the folder directory and make sure you have composer installed on your device

**Comment by Malika3** [comment]
yes it works! thanks
