### ISSUE TITLE
Google Analytics Integration not working 

### ISSUE THREAD

**Issue by amrit-citrusleaf** [cnvs/canvas#360]
I updated the Google Analytics Client ID in the admin panel but I can't see any activity in my Google Analytics Panel. Any thoughts on why this is happening?

PS- Thanks for this wonderful piece of software! :)

**Comment by austintoddj** [comment]
Glad you're liking it @amrit-citrusleaf! So entering your tracking code in the admin section isn't making it visible on the frontend pages?

**Comment by amrit-citrusleaf** [comment]
@austintoddj : Just checked, the analytics is working fine. We can close this issue.
