### ISSUE TITLE
GET http://localhost/vendor/canvas/assets/js/frontend.js net::ERR_ABORTED

### ISSUE THREAD

**Issue by kakekcoding** [cnvs/canvas#361]
Hi! I have a problem in my canvas.
`GET http://localhost/vendor/canvas/assets/js/frontend.js net::ERR_ABORTED
GET http://localhost/vendor/canvas/assets/css/frontend.css net::ERR_ABORTED
GET http://localhost/vendor/canvas/assets/css/frontend.css net::ERR_ABORTED
GET http://localhost/vendor/canvas/assets/js/frontend.js 404 (Not Found)`

Please help me.

**Comment by Acen** [comment]
I don't think `vendor` is publically accessible by default. Not sure why that's happening. Is there a vendor publish command linked with canvas?

**Comment by austintoddj** [comment]
Thanks for helping out @Acen.
