### ISSUE TITLE
How to import the exported archive?

### ISSUE THREAD

**Issue by amrit-citrusleaf** [cnvs/canvas#363]
I wish to move the database from sqlite to PostgreSQL and to do so, I started by exporting the archive. I wonder how to import this archive in a fresh Canvas install. Please help.

**Comment by austintoddj** [comment]
@amrit-citrusleaf Unfortunately, there is no automated way to import the archive. 

You can however import the .csv files into your database via a client (ie. Sequel Pro, Navicat), and then manually add in whatever images were publicly uploaded.
