### ISSUE TITLE
Command canvas:update is not updating

### ISSUE THREAD

**Issue by nielvrom** [cnvs/canvas#365]
In the admin area of canvas I see the message _"Canvas v3.4.2 is available! Please update now."_. 

When I run the command `php artisan canvas:update` and say "yes" when the console ask me to the update the Canvas core I'm getting the following output:

 Welcome to the Canvas Update Wizard! You'll be back at it in no time...

You are running Canvas core: v3.0.5. The latest version available is: v3.4.2.
Update Canvas core? (yes/no) [no]:
 >

Publishing core package assets...
 5/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
✔ Success! Canvas core assets have been published.

Building the search index...
 5/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
✔ Success! The application search index has been built.

Finishing the update...
 5/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
✔ Canvas has been updated.

+------------------+-------------+
| Previous Version | New Version |
+------------------+-------------+
| v3.0.5                    | v3.0.5      |
+------------------+-------------+

As you can see it's not updated and the message is still showing in admin area. Why it doesn't update?

In my **composer.json** I have:

```
"require": {
        "laravel/framework": "5.3.*",
        "cnvs/easel": "3.0.*",
        "cnvs/paper-dark": "*",
        "doctrine/dbal": "^2.5"
    },
```

**Comment by austintoddj** [comment]
Thanks for submitting this @nielvrom. I'll take a look and let you know what I find out.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
