### ISSUE TITLE
Numbers unable to be used in Blog Title

### ISSUE THREAD

**Issue by glennmcewan** [cnvs/canvas#366]
It looks like the default theme doesn't like numbers. I tried entering `S2000` in to the blog title, but weird glyphs have appeared.

Below is a screenshot from the homepage:

<img width="370" alt="screen shot 2018-01-03 at 20 38 51" src="https://user-images.githubusercontent.com/10562256/34538917-47ca4aee-f0c6-11e7-8b3b-74e86818754f.png">

**Comment by austintoddj** [comment]
Closing now since this won't be an issue with the next version of Canvas.
