### ISSUE TITLE
[PHP 7.2] Canvas install fails due to trying to count the uncountable

### ISSUE THREAD

**Issue by SlyDave** [cnvs/canvas#367]
```
[✔] Success! Your admin user account has been created.

 Step 2/3: Blog title:
 > xxxxx

[✔] Success! The title of the blog has been saved.

 Step 3/3: Blog subtitle:
 > xxxxxxxxxxxxxxx

[✔] Success! The subtitle of the blog has been saved.

Writing the search index...
Creating a unique application key...
Finishing up the installation process...

   ######       ##      ####     ##  ##      ##   ##       ########
  ##////##     ####    /##/##   /## /##     /##  ####     ##//////
 ##    //     ##//##   /##//##  /## /##     /## ##//##   /##
/##          ##  //##  /## //## /## //##    ## ##  //##  /#########
/##         ########## /##  //##/##  //##  ## ########## ////////##
//##    ## /##//////## /##   //####   //#### /##//////##        /##
 //######  /##     /## /##    //###    //##  /##     /##  ########
  //////   //      //  //      ///      //   //      //  ////////


An unexpected error occurred. Installation could not continue.
[✘] count(): Parameter must be an array or an object that implements Countable

Please run the installer again.

If this error persists please consult https://github.com/cnvs/easel/issues.
```

This is a PHP 7.2 incompatibility when using count() on uncountables (i.e. non-arrays or objects not implementing Countable interface (or ArrayAccess etc.))

**Comment by glennmcewan** [comment]
Thanks for the issue report, although PHP 7.2 is not currently supported by the latest version of Canvas, due to the version of Laravel currently being used.

It’s something we will be working towards shortly, but for now Canvas will only be guaranteed to run on <=7.1.

I will update the composer.json file later to include a hard limit so that composer will flag the 7.2 incompatibility.

**Comment by SlyDave** [comment]
Thanks for the fast response.

I would however note that Laravel's support is `"php": ">=7.0.0",` (https://github.com/laravel/laravel/blob/master/composer.json)

And laravel 5.5 is running just fine on PHP 7.2

Hope you take that into consideration for your Laravel 5.3 to 5.5 upgrade

**Comment by glennmcewan** [comment]
If you take a quick look at the issue in cnvs/easel#162 I have included a link to the portion of Laravel 5.3 itself which is causing the issue.

Once Canvas’ depency on Laravel is upgraded to 5.5, which is tested on 7.2 by Travis, then Canvas will support the same versions. I’ll let you know once we’ve upgraded the Laravel dependency.

**Comment by ibnujakaria** [comment]
Is there any consideration to upgrade the laravel used in canvas to version 5.7?

**Comment by austintoddj** [comment]
@ibnujakaria That'll be covered in v4.0 of the application. There's not a set release date yet, but keep your eyes on the `develop` branch of [Canvas](https://github.com/cnvs/canvas) to see the progress.
