### ISSUE TITLE
Route [login] not defined. Adding canvas to fresh Laravel installation

### ISSUE THREAD

**Issue by lukio3** [cnvs/canvas#370]
**To Repro:**
Following a fresh Laravel Framework 5.6 installation
Using your guide: _https://cnvs.readme.io/v3.3/docs/integrating-canvas-in-an-existing-project_

Following the steps I can see my **/blog** route in the browser with the example blog post but cannot access **/admin** route.

I get the following error: 

```
InvalidArgumentException
Route [login] not defined.
```

It seems like the routing is getting confused with the default laravel routing somewhere? I don't get this error when installing cnvs as a standalone app. Do you know a way around this?

The shortfall of installing as a standalone app seems to be I can't customise with vue.js2 as I would with a fresh Laravel 5.6 installation.

**Steps i've tried:**
If I run **php artisan make:auth** (not part of the steps) then I can only access the default authentication routes.

**Comment by austintoddj** [comment]
First off, thanks for taking the time to create the issue. Closing because everything v3.x related will remain as-is and won’t receive anymore updates. The next release is slated for this week, so stay tuned!
