### ISSUE TITLE
assets and views will be deleted

### ISSUE THREAD

**Issue by hatamiarash7** [cnvs/canvas#372]
Hi
I have some problems here and i can't understand the reasons

After `php artisan vendor:publish` i have some assets and views and i added some css, js, etc too. But they are gone after update canvas's settings ( add Google Analytics ) !! also i lost any changes of original files like `frontend.css`  

What's going on here ? is this an option of Canvas ?

**Comment by austintoddj** [comment]
Can't say for sure without replicating the issue. Your assets and views should not be overwritten.

Unfortunately I've been a bit behind on upgrading Canvas, so I'm sure many of the dependencies are a bit out of date and there are some breaking issues. Planning to re-work this soon, thanks for checking it out!

**Comment by hatamiarash7** [comment]
I looked at your codes and find the problem.
In `SettingsController@store()` we have this line

`$this->themeManager->setActiveTheme($request->input('theme'));`

And in `ThemeManager@setActiveTheme()` function at line **193** & **195** we are publishing new assets that removed everything in assets and replacing new ones ...

This process is very good when we want using Default themes ( paper / paper Dark ). But when we changed project's assets file, everything will be disappeared after update !
Maybe we need a **Custom Theme** option that prevent this problem

**Comment by craigh411** [comment]
@hatamiarash7 Thanks for tracking down that piece of code, here's how to get around this issue:

Firstly Create a new SessionsController in the project that extends the Canvas Sessions Controller, then override the store method and copy the code from the original canvas method and just change the line you suggested to:
```php
if($request->toArray()['theme'] !== 'custom'){
   $this->themeManager->setActiveTheme($request->toArray()['theme']);
}
```

Now add a route to `routes/web.php`
```
Route::post('/settings', 'SettingsController@store')->name('admin.settings');
```
Then in `resources/assets/views/vendor/canvas/backend/settings/partials/form/settings.blade.php` change the post route:
```HTML
<form class="keyboard-save" role="form" method="POST" id="settings" action="{!! route('admin.settings') !!}">
```

And finally add a custom option to the select:
```HTML
<select name="theme" id="theme" class="selectpicker">
  <option @if ($data['active_theme'] == "default") selected @endif value="default">{!! $data['default_theme_name'] !!}</option>
  @foreach($data['themes'] as $themeId => $themeName)
  <option @if ($data['active_theme'] == $themeId) selected @endif value="{!! $themeId !!}">{{ $themeName }}</option>
  @endforeach
  <option value="custom">Custom Theme</option>
</select>
```
