### ISSUE TITLE
Missing Database Columns

### ISSUE THREAD

**Issue by ebaum** [cnvs/canvas#373]
Fresh installation and there are missing database columns. role is missing from users. user_id and is_published missing from canvas_posts.

**Comment by achieveforum** [comment]
We're encountering a similar issue on a fresh install. When the installer tries to add the admin user account it's throws an error stating that the role column cannot be found on the canvas_users table.

I checked the migrations in the DB and sure enough it looks like about half the migrations are not run at this point.

Any update on this issue? The original issue was reported 15 days a go with no reply yet.

**Comment by austintoddj** [comment]
The old documentation can be found [here](https://cnvs.readme.io/v3.1/docs). Closing now because this won't be an issue in the next version of Canvas.
