### ISSUE TITLE
Change content_raw and content_html columns to MediumText

### ISSUE THREAD

**Issue by craigh411** [cnvs/canvas#374]
The current migrations use `TEXT` as the column type for `content_raw` and `content_html`, however, `TEXT` has a limit of ~65,000 characters. Generally, this is enough, however if you have a large HTML table, it's easy to exceed this limit due to the amount of markup needed. It should be easy enough to create a migration that makes this change, but [per this issue](https://github.com/laravel/framework/issues/21847), Laravel does not correctly change a `TEXT` column to a `MEDIUMTEXT`, which means it has to be done manually. It would be nice to have these columns as `MEDIUMTEXT` by default to avoid this potential issue.

**Comment by cbotsikas** [comment]
Hi @craigh411 , I'm not sure what and where you want to change, but i've seen this issue from the refered one. You might be interested in my work around: https://github.com/singularlogic/ToyLabs/blob/develop/database/migrations/2018_06_09_012721_update_market_analysis_tables.php
On this migration i'm changing three tables' columns 'anlzer_data', 'data' and 'settings' to longText from normal Text, so you'll have to adjust. The idea is that i'm creating new longText columns, copying data, dropping old columns and finally renaming the new columns..

**Comment by austintoddj** [comment]
Closing since this won't be an issue with the next version of Canvas.
