### ISSUE TITLE
Problem with tags page

### ISSUE THREAD

**Issue by detector-v** [cnvs/canvas#415]
hello, i have a problem.

when I go to the page by the link tag, the site writes an error:

"compact(): Undefined variable: operator
--
in Builder.php line 1229"
more info on scr:
![image](https://user-images.githubusercontent.com/3055001/50688971-e3593c80-1038-11e9-879b-3c5611030cfd.png)

**Comment by austintoddj** [comment]
What version of Laravel are you running this on?

**Comment by detector-v** [comment]
Laravel Framework 5.4.36

**Comment by austintoddj** [comment]
Work on v4.0 is the priority now and we’re not pushing anymore updates to the v3.* platform. If you can hold out a little longer, the next release should be all you need.

**Comment by detector-v** [comment]
Ok, tnx for the answer.
I'll wait.
