### ISSUE TITLE
Problem with MediaManager on Dark theme

### ISSUE THREAD

**Issue by detector-v** [cnvs/canvas#417]
Hello,
i have a problem.

When I turn on the dark theme, the plugin Media Manager disappears in the admin panel.

![image](https://user-images.githubusercontent.com/3055001/50695413-a0559400-104d-11e9-9ae7-4814ea380e04.png)

**Comment by austintoddj** [comment]
Are there any errors in the console when you do that?

**Comment by detector-v** [comment]
Only this bag/error.
apart from this: https://github.com/cnvs/canvas/issues/415

**Comment by austintoddj** [comment]
Work on v4.0 is the priority now and we’re not pushing anymore updates to the v3.* platform. If you can hold out a little longer, the next release should be all you need.
