### ISSUE TITLE
USAGE WITH EXISTING LUMEN-PROJECT

### ISSUE THREAD

**Issue by arashifunsho** [cnvs/canvas#432]
How do I integrate this into my existing lumen project; I'm trying to add blog functionality to my mobile app; but the content will be managed by an admin from a frontend. Decided to see if there a ready-made blog package I can install to save development time and came across this one.

I'll appreciate it if you can point me in the right direction.

**Comment by austintoddj** [comment]
I've never attempted to add this to a Lumen app, but let me give it a go and get back to you on it.

**Comment by arashifunsho** [comment]
Thanks, I figured I should create a new laravel project and install canvas into that. Blog feature is just an addon and so I can always reference the link in a webview in my app.... Thanks anyways. 

Awesome job with this library
