### ISSUE TITLE
Route [login] not defined when you visit http://127.0.0.1:8000/canvas

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#433]
I went through the following installation steps:
```
laravel new cnvs
cd cnvs/
composer require cnvs/canvas
php artisan canvas:install
php artisan storage:link
php artisan canvas:setup
composer update
php artisan migrate
php artisan vendor:publish --tag=canvas-assets --force

```
Then, going to http://127.0.0.1:8000/canvas

Gives this error:
InvalidArgumentException
Route [login] not defined.

Details:
/Users/Code/CMS_samples/cnvs/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php
               ! ($expires && Carbon::now()->getTimestamp() > $expires);
    }
 
    /**
     * Get the URL to a named route.
     *
     * @param  string  $name
     * @param  mixed   $parameters
     * @param  bool  $absolute
     * @return string
     *
     * @throws \InvalidArgumentException
     */
    public function route($name, $parameters = [], $absolute = true)
    {
        if (! is_null($route = $this->routes->getByName($name))) {
            return $this->toRoute($route, $parameters, $absolute);
        }
 
        throw new InvalidArgumentException("Route [{$name}] not defined.");
    }
 
    /**
     * Get the URL for a given route instance.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  mixed  $parameters
     * @param  bool   $absolute
     * @return string
     *
     * @throws \Illuminate\Routing\Exceptions\UrlGenerationException
     */
    protected function toRoute($route, $parameters, $absolute)
    {
        return $this->routeUrl()->to(
            $route, $this->formatParameters($parameters), $absolute
        );
    }
 
    /**
Arguments
"Route [login] not defined."

**Comment by paprykasz** [comment]
Hi @connecteev , I think you forgot:

> Note: Canvas requires you to have user authentication in place prior to installation. You may run the make:auth Artisan command to satisfy this requirement.

**Comment by austintoddj** [comment]
@paprykasz is right. That should fix your issue.

**Comment by connecteev** [comment]
@paprykasz @austintoddj thank you, that fixed the issue.
