### ISSUE TITLE
Adding a category / sub-category tree to canvas

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#434]
Possible to add a category / sub-category tree to canvas? We have gotten to use Wordpress and its categories and tags, I believe Ghost does the same as well? 😀 I think it would make cnvs more solid as a laravel blogging platform, and this is a fairly common use-case imo.

See how wordpress does it here: https://prnt.sc/m4jnjs
(this is one of those features of wordpress that is actually really well executed)

Tags are for search, categories for browse....they shouldn't be overlapping. Besides being a one-to-many relationship (like tags-posts) between posts and categories, the difference is that the UX for assigning one or more categories to a post should not be "Free form" like tags.

Here's a use-case for showing "latest posts in category xx"
https://prnt.sc/m4jtct
URL: http://fullratchet.net/ep40-crowdfunding-the-socialization-of-finance-jon-medved/

You could technically do this with tags (iterate through the latest posts in tag xxx, and the user doesn't have to know whether it's a tag or category. But...tags dont have a hierarchy, categories do...and they give you a lot of flexibility to allow the user to browse content by looking through the category tree - which can be presented in a multitude of ways, in menus, in sidebars, etc)

Categories can also be parts of fancy URLs like `my.blog/travel/trip-to-cyprus`, or: `my.blog/recipes/my-favorite-soup`, where `travel` and `recipes` are category slugs.

**Comment by austintoddj** [comment]
Not a bad idea as it is pretty standard for blogs. Let me think about it for a bit and I'll let you know.
