### ISSUE TITLE
Error: "Illegal string offset 'slug'" seen after saving a new post

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#439]
Using the latest version of laravel (5.8) and latest canvas.
Create a new post with a topic. On saving, I see this error:
Error: "Illegal string offset 'slug'" seen after saving a new post

Screenshot: https://prnt.sc/mryraj

**Comment by austintoddj** [comment]
Did you re-publish the assets after updating?

**Comment by austintoddj** [comment]
Thanks for bringing this up. Fixed with [v4.1.5](https://github.com/cnvs/canvas/releases/tag/v4.1.5)

**Comment by connecteev** [comment]
My pleasure, @austintoddj  and thanks for the fast fix.
