### ISSUE TITLE
Multi-language Support

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#447]
I really liked cnvs / canvas and I will certainly use it in my projects. However, I'm having some language difficulties. My clients speak Portuguese and for this reason I am having to translate the views into my language. When doing this I saw that they have little text and I had the idea to make some adaptations in the project to support multi-languages. Would you like to know how to control for the project by making these adaptations?

Thanks for listening!

**Comment by austintoddj** [comment]
Sure. If you’d like to submit a PR with your proposed changes I’d be happy to take a look!

**Comment by Yo1L** [comment]
Hello,

First things first, your package is awesome! 👍 
If we could publish the canvas views (resources/views), it will permits to fully adapt/translate as we please.

Thx

**Comment by austintoddj** [comment]
Currently working on translating the package views. Since the two of you brought this up the first translations are Portugese and French. I'll tag this issue when it's merged in.

**Comment by albertoelias123** [comment]
I'm also working on the translation. I'm currently replacing all the words in the view with "Translation Strings" as per the Laravel (Localization) documentation.

**Comment by austintoddj** [comment]
One thing that I'm noticing off the bat that will cause issues with being translated are input placeholders. Once the bulk of the content is translated I'll put some thought into these.

**Comment by Yo1L** [comment]
Tell me if I can help?
Maybe review the French translation?

**Comment by austintoddj** [comment]
Will do. Almost got it all wrapped up here so I'll let you know and you can see how well Google Translate did for me 😅

**Comment by Yo1L** [comment]
Hahaha You should try deepl :)

**Comment by austintoddj** [comment]
@albertoelias123 @Yo1L Go ahead and upgrade your apps to the latest version `v4.1.29` and let me know if any of the translations look incorrect to you. The base Laravel app that you have Canvas installed in will determine the locale that Canvas uses.

Let me know if you have any questions!

**Comment by Yo1L** [comment]
Thanx @austintoddj, I'm gonna check that :)

**Comment by Yo1L** [comment]
Sorry @austintoddj, I edited only so you may have 5-6 waiting PR.
Thanx a lot

**Comment by austintoddj** [comment]
Feature added in [v4.1.29](https://github.com/cnvs/canvas/releases/tag/v4.1.29)
