### ISSUE TITLE
Cant run canvas:install

### ISSUE THREAD

**Issue by IjayN** [cnvs/canvas#471]
![image](https://user-images.githubusercontent.com/28860678/56966689-5480aa80-6b68-11e9-97eb-e55a342b2e85.png)

This is the error im getting while trying to run canvas:install
Im using laravel 5.7 with mysql database
Assistance would be greatly appreciated

**Comment by austintoddj** [comment]
Have you defined the database credentials properly in the `.env` file?

**Comment by IjayN** [comment]
> Have you defined the database credentials properly in the `.env` file?

Yeah...i've double checked them

Im using phpmyadmin ....can that be the problem??

**Comment by austintoddj** [comment]
What are you using to serve the application? Valet, Homestead or something else?

**Comment by IjayN** [comment]
> What are you using to serve the application? Valet, Homestead or something else?
> 
> And when setting up the base Laravel app, you were able to run the migrations just fine?

I'm using homestead ....The migrations run just fine....and the authentication scaffolding too...the error arises when i ran canvas:install

**Comment by austintoddj** [comment]
What version of MariaDB do you have installed? Looks like the JSON data type support was added in 10.2, so anything less than that could throw your error. Canvas uses JSON to store post metadata, so updating your version if possible is a potential fix for you.

**Comment by kavierkoo** [comment]
I am having the same issue, seems like my MariaDB using v10.1 :(

**Comment by austintoddj** [comment]
Closing this issue now, let me know if it still persists or if you run into anything else.
