### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by technodesign-dn** [cnvs/canvas#475]
Как отобразить поиск на главной странице? Будет ли это реализовано?

**Comment by austintoddj** [comment]
Если вам нужна функциональность поиска в веб-интерфейсе блога, вам придется создать его самостоятельно.

Если вы используете установку по умолчанию, выполнив команду Artisan `canvas: setup`, то у вас будут опубликованы виды и контроллер для вашей установки Laravel.

Вы можете расширять его по своему усмотрению, но в настоящее время поиск не поддерживается шаблоном по умолчанию.
