### ISSUE TITLE
Error php version

### ISSUE THREAD

**Issue by technodesign-dn** [cnvs/canvas#476]
![image](https://user-images.githubusercontent.com/45261338/57765302-d1d22080-770d-11e9-9a82-76ce78e41fbd.png)
![image](https://user-images.githubusercontent.com/45261338/57765365-f8905700-770d-11e9-9320-c55975c24677.png)

my version php 7.2

**Comment by austintoddj** [comment]
Looks like you're trying to install `^3.4`. The latest supported version of Canvas is `^4.1`.

**Comment by technodesign-dn** [comment]
Пользуюсь инструкцией composer require cnvs/canvas

**Comment by austintoddj** [comment]
Я просто запустил `composer require cnvs/canvas` и установил версию `^ 4.1`. Не могли бы вы попробовать это на новой установке Laravel 5.8 и снова выполнить шаги установки?

**Comment by technodesign-dn** [comment]
Неплохо бы сделать полноценную "Canvas CMS"

**Comment by austintoddj** [comment]
Вы правы, это было бы здорово! Спасибо за предложение!
