### ISSUE TITLE
Suggestion: Page CRUD

### ISSUE THREAD

**Issue by soipo** [cnvs/canvas#484]
Hi there,
i think it would be a nice thing to add a Page CRUD, what do you think ?
I  would be happy to code it.

**Comment by austintoddj** [comment]
Thanks for the suggestion! Is your intention to flesh out the package and make it more of a CMS? Older versions of Canvas were more along those lines. This is how I see the scope of the project today:

_Re-create Medium as an easily consumable Laravel package, with a few enhancements._

So while it'd be neat to add page functionality, I'd like to continue giving developers a _Medium-esque_ experience, but on a platform of their choice.

**Comment by soipo** [comment]
I agree with you, but 99% of the times we also need few pages, and adding it to this bundle it would be great, no intention to work on yet another CMS, that's what I liked about this project, it's NOT a CMS.

**Comment by austintoddj** [comment]
Closing this since it's not the direction Canvas will go in the near future, but open for PRs or suggestions on what this could look like.
