### ISSUE TITLE
Suggestion: Allow selection of Author within a post's settings

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#488]
Wink (https://github.com/writingink/wink) allows you to do this in 'general settings'. You can select an Author from a dropdown:
https://1ce.org/1#SkAHpx6a4

**Comment by austintoddj** [comment]
Thanks for the suggestion! Although I see where you're going with this, I'm going to close this one for 2 reasons:

1. Users should not be writing or authoring content for another user. If you log in and publish anything, the content will be associated with your user. This keeps it a bit more like Medium and less like a conventional CMS.

2. If a dropdown of users were supplied, it'd be reliant on the default Laravel setup, ie. a `users` table with the default fields. I'd like to keep this as agnostic as possible, and there are only a few times that `auth()->user()` is actually called. If someone's application uses a different base user setup, I'd like the application to still function the same.

Let me know if you've got another solution.

**Comment by connecteev** [comment]
@austintoddj Makes sense to me, thanks for the thoughtful response! If I think of something else here I'll let you know.
