### ISSUE TITLE
Suggestion: Allow the featured image to be added / edited / deleted from the main post edit page

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#489]
When editing a post from:
http://127.0.0.1:8001/canvas/posts/aeb35aec-8efb-4fac-8fa6-cce71606b66f/edit
See https://prnt.sc/nv9dzq

You cannot view / edit / delete the post's featured image from here. This is a bit annoying.

Allow the featured image to be added / edited / deleted from the main post edit page instead of having to click on 'featured image' from the menu.

**Comment by austintoddj** [comment]
Not a bad suggestion. I'll give it some thought and update this if it's going to be included in a future release.

**Comment by austintoddj** [comment]
It's a good idea, but I prefer to keep the editing strictly to the actual editor screen.
