### ISSUE TITLE
Suggestion: Allow a post to be associated with other (Related) posts

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#491]
Allow a post to be associated with other (Related) posts

Those (related) posts can then be shown on the individual post page, like on the bottom of this blog: https://spreadprivacy.com/how-to-be-anonymous-online/

**Comment by austintoddj** [comment]
Currently, the tags system is used for pulling related content together. 

In the default template, the 2 links that could potentially show at the bottom of a post are sorted as follows:

<img width="1280" alt="Screen Shot 2019-06-12 at 2 24 34 PM" src="https://user-images.githubusercontent.com/8037011/59380665-39848700-8d1f-11e9-9b4a-4426b54c3648.png">

- _Read This Next_ - The next published post based on the published date
- _You Might Enjoy_ - Another post sharing the same tag as the one currently being read

Granted, this doesn't allow you to "link" posts together and create a series, but I believe tags are a sufficient way of grouping the posts together.

**Comment by connecteev** [comment]
That's fair :) I can make do with tags for now. Thanks for the explanation.
