### ISSUE TITLE
Suggestion: Add option to seed Canvas from the package itself

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#494]
Suggestion: Add option to seed Canvas from the package itself. I did this in the Laravel app below but I don't know how to add / run a seeder from within the package, else I probably would've created a pull request.

See my commit here, which works rather well:
https://github.com/connecteev/laravel-blog-built-on-cnvs/commit/ee628ad7f69a2f380a5fadab1b354e9df38f165a

**Comment by austintoddj** [comment]
Good suggestion! I'll see what I can do to get something like this as an optional setup feature.

**Comment by connecteev** [comment]
@austintoddj sweet! and you have 95% of the code already (link above!)

**Comment by austintoddj** [comment]
Feature added in [v4.2.3](https://github.com/cnvs/canvas/commit/e9c864df5ebd4ebe54de3042bde49bf409e6c5bf)

**Comment by connecteev** [comment]
@austintoddj works great, thanks for including in the package, will help others get up and running quickly ;)
Just an idea, may be good to add the command 
```
php artisan canvas:setup --data
```
to the readme.md file so others know this functionality exists..
