### ISSUE TITLE
SEO cards og:title and twitter:title using description

### ISSUE THREAD

**Issue by Darival** [cnvs/canvas#496]
meta tags og:description and twitter:title are both using og_description and twitter_description respectively, probably a mistake from copy pasting.

**Comment by Darival** [comment]
im already doing he pr to fix this

**Comment by austintoddj** [comment]
Thanks for the help @Darival. Just merged it in and it'll be available on the next release.

**Comment by connecteev** [comment]
I noticed this too, thanks for the fix @Darival @austintoddj
