### ISSUE TITLE
Suggestion: API Blog and Rename Language

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#500]
Hi, I added a Blog API and renamed some language pack according to ISO-639 (https://en.wikipedia.org/wiki/ISO_639).

**Comment by austintoddj** [comment]
Fixed in [v4.2.3](https://github.com/cnvs/canvas/commit/e9c864df5ebd4ebe54de3042bde49bf409e6c5bf)

I didn't add the blog api yet since that is more of a user-specific option. If someone wants to extend the default controller then they are free to do that.

Thanks for the update on the language!
