### ISSUE TITLE
Create draft slug automatically from post title after the title is entered

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#505]
This is a huge source of frustration for me, especially as I launch my Laravel project and use Cnvs in production. 

Steps:
Go to the Canvas Admin: http://127.0.0.1:8001/canvas/posts
Click 'New Post' which takes you to http://127.0.0.1:8001/canvas/posts/create
Enter a Title 'This is an introduction to Web Analytics"
Then if you check the post's "General settings", the Slug is set to something random like:
post-256c2714-ccec-46bf-9fed-baf9be5f396d

Can't we slugify this?
Laravel supports this feature out of the box, we don't even need a 3rd party package:
See https://laravel.com/docs/master/helpers#method-str-slug
```
use Illuminate\Support\Str;
$slug = Str::slug('This is an introduction to Web Analytics', '-');
```
// should create the slug: this-is-an-introduction-to-web-analytics

The logic would be:
1. If the slug is NULL (or in the default post-xxxxxxxx format), call Str::slug to slugify.
2. If the slug is not NULL (or not in the default post-xxxxxxxx format), it means the admin had modified it, so it should not be changed / slugified.
I imagine that this is a super quick fix, would really love to see this one done soon! 

Note: There is a corner case where you may add the title, view the slug, edit the title again before saving the post. In this case, until the post has been saved, it's preferred that the slug change to reflect the new title. However, if this is too much to handle, this is a corner case and can be ignored.

**Comment by tkaravou** [comment]
👍 

I'd also make the reco to allow for slashes `/` in slugs. For example, you might want to have a url that's `topics/food/lasagna` but that's currently not allowed.

**Comment by connecteev** [comment]
@tkaravou what you're describing is a path, not a slug though. You probably want to have a hierarchy of topics instead... slashes in slugs aren't typical...my 2c

**Comment by tkaravou** [comment]
@connecteev You're right, what I'm asking for is a path rather than a slug. It makes a lot of sense to use paths rather than slugs for posts for SEO reasons. I can assist in adding this functionality if anyone else is interested.

**Comment by connecteev** [comment]
@tkaravou I'm for it, but I defer to @austintoddj on whether he would entertain a PR for this issue.

**Comment by austintoddj** [comment]
I'd be more than happy to check out a PR if anyone submits one.
