### ISSUE TITLE
Suggestion: Allow an option to Edit HTML Markup

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#507]
Canvas is great as a WYSIWYG editor, and has the ability to add/embed HTML markup, but there's no way to view / edit the HTML, other than going to the database to do it. Sometimes I need to dig into the HTML code, because the WYSIWYG editor is lacking in functionality (tables, colors, lists, and so on and so forth). 

It would be great to have an option to "Edit HTML Markup" and borrow that code from any of the popular CMS's. 

https://prnt.sc/o0n14e

**Comment by austintoddj** [comment]
Good thought. I'll see what I can do!

**Comment by austintoddj** [comment]
Fixed in [v5.2](https://github.com/cnvs/canvas/blob/master/changelog.md#520-february-9-2020)

Simply clicking on the embedded content will open a modal where you can edit the markup.
