### ISSUE TITLE
Suggestion: Allow cnvs to be installed to a different database from the main laravel instance

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#509]
Hey @austintoddj ! Here's another one for you. Hope you're not overwhelmed with these thoughts and ideas....once I have more time and figure out how laravel packages work, I may be able to contribute a PR or two. Anyway here goes..

I am trying to keep the 'users' table (and other tables) for the admin (and used by cnvs) separate from the database of my main Laravel app. Having them share the same users table (or database for that matter) isn't ideal.

As you know, the writingink/wink package (which I am no longer using thanks to Cnvs) does this.

Proposed configuration settings to allow cnvs to be installed to a different database from the main Laravel instance:

In config/canvas.php:
```
    'database_connection' => env('CANVAS_DB_CONNECTION', env('DB_CONNECTION')),
```

In .env:
```
CANVAS_DB_CONNECTION='xxxxxxxxx'
```

Note: Cnvs could still default to using the main Laravel app, unless configured otherwise.

On a related note, some food for thought: Calling ```php artisan migrate``` also installs the Canvas tables. Terminal Output:
```
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_07_30_234137_create_podcastepisodes_table
Migrated:  2018_07_30_234137_create_podcastepisodes_table
Migrating: 2018_10_12_000000_create_canvas_tables
Migrated:  2018_10_12_000000_create_canvas_tables
Migrating: 2019_01_16_122616_create_pm_course_dates_table
Migrated:  2019_01_16_122616_create_pm_course_dates_table
Migrating: 2019_02_16_000000_create_canvas_topics_tables
Migrated:  2019_02_16_000000_create_canvas_topics_tables
Migrating: 2019_03_05_000000_add_indexes_to_canvas_views
Migrated:  2019_03_05_000000_add_indexes_to_canvas_views
```
This is probably okay, or does it make sense to call the Canvas DB migrations only when ```php artisan canvas:install``` is called? This latter part may or may not be related to the main request above (keeping the DB's separate, which is probably a valid feature imo).

**Comment by austintoddj** [comment]
First off, not overwhelmed by these suggestions at all. I really appreciate the time and effort you're putting in with the project, it's making it better with each issue.

Let me see what I can do about this and I'll update here with more info.

**Comment by connecteev** [comment]
@austintoddj awesome :-) I want nothing more than to make cnvs even better than it already is. It's amazing that there is nothing comes close as far as a lightweight Laravel CMS is concerned....Cnvs does a great job but it could be so much better. Let's make that happen. 
Curious what you come up with to solve this one..

**Comment by austintoddj** [comment]
Coming back to this..

I like the thought, however I'm comfortable keeping the database structure as-is. Perhaps if in the future there is more of a need here, I'll look into it again. But for now, I'd like to keep it as simple as possible. 

Thanks for the idea though!

**Comment by ibrahim-mubarak** [comment]
This is something we are also looking for.

One more option is to allow overriding the model itself so we could update such properties in addition to something else if needed.

**Comment by austintoddj** [comment]
@ibrahim-mubarak What would it look like to allow overriding like that?

**Comment by Itemshopp** [comment]
This could be a great new feature actually, would you be interested in a possible PR proposal ?

**Comment by austintoddj** [comment]
Feel free to PR to the `develop` branch and I'll review 😄
