### ISSUE TITLE
Question: How to extend the canvas tables with additional fields

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#510]
@austintoddj this is more of a question for you.

Here's another real use-case I ran into:
I am trying to update the authors (users table) by adding new fields for image, author username, bio, etc.
```
$post->author->image = '/img/authors/kp.jpg'; // author image URL (relative or absolute)
$post->author->url = '/author/kp123'; // author URL, so front-end can point to http://127.0.0.1:8001/author/kp123
$post->author->bio = 'KP is the founder of .......'; // author bio
```

Also, I am trying to update the posts table with additional fields, like so:
```$post->isPremium=1; // 0 or 1, for free/paid content, for example```

I still want to be able to inherit all the goodness of this package as it's development continues, by simply running 'composer update' to update my version of cnvs going forward. This means I want to extend these tables in a way that does not involve forking cnvs or modifying the source code. Is what I need as simple as just creating 2 migration files for 'users' and 'posts'? Your thoughts are appreciated. Btw I still think #509 is highly desirable, no matter what the answer to this one :)
ps. you really should make me a core member of cnvs at this point...lol

**Comment by austintoddj** [comment]
It's very beneficial to hear real-world examples, so thanks. 

I have a few thoughts in mind about how this might be achieved, but I'll need to give it a bit more thought. I'll update here when I've got something for you.

**Comment by connecteev** [comment]
@austintoddj the feeling's mutual, can't tell you how much I appreciate your responsiveness.
I'll be patiently waiting for your thoughts on this.

**Comment by connecteev** [comment]
@austintoddj no pressure but would love your thoughts on this

**Comment by austintoddj** [comment]
Still putting some ideas together, but yes, you could go ahead and create migrations to extend those tables if you choose.

The one caveat to this is on the Posts table. Extending the existing tables is fine **only** if the new fields you're adding are either _nullable_ or have a _default value_ set. If you were to add a field without setting that up in your migration, then the package will try to save records and and hit a fatal error.

Since the Users table is never acted upon, you'd be free to add whatever you like to that table.

As far as the CRUD for those new fields, that'd be something you'd have to create yourself.

**Comment by connecteev** [comment]
@austintoddj appreciate the thoughts here....thanks for mentioning the fatal error, that would be frustrating if default values were not set. 
The problem still is that creating CRUD for the new fields would require updating the cnvs package itself (unless I am missing something). For example, how would you allow the value of $post->author->image, $post->author->url etc from the cnvs admin? Would that not mean changing the package in some way? Maybe there's a workaround here....maybe there is a clean way to hook into cnvs without updating the package itself.

**Comment by austintoddj** [comment]
I wasn't necessarily thinking that the custom fields would be added to the admin section of the package. Making a tool that extends the package in a way similar to Laravel Nova with custom fields etc. is worth thinking about, but I don't know about the implementation.

My thought was a bit more of a hack, where you could create your migrations, create models in your own project that extend the package models, and then handle the CRUD on your application side. Like I said, way more work and prone to errors.

I'll keep this in mind going forward, but right now there's not a _clean_ way to add custom fields.

**Comment by connecteev** [comment]
Thanks Todd, appreciate the thoughts here, but this was the response I was afraid of :)

**Comment by connecteev** [comment]
@austintoddj Just found this https://github.com/tightenco/parental
Thoughts and any way to integrate this into Cnvs to do the above?

**Comment by austintoddj** [comment]
That's really interesting, I've never run across this package before. I'll check it out though and see what it can do!

**Comment by connecteev** [comment]
Yes, I'm curious what you think about it and whether you can use this (or some other solution) to extend canvas elegantly, so I am still "in sync" with the future changes coming to canvas.

**Comment by connecteev** [comment]
@austintoddj take a look at this PR and the comments within it.
https://github.com/writingink/wink/pull/140
You know as they say...
```good artists copy great artists steal``` 👯‍♂

**Comment by connecteev** [comment]
@austintoddj see https://github.com/writingink/wink/issues/92 and this PR: https://github.com/writingink/wink/pull/140 for how wink does this

**Comment by austintoddj** [comment]
While there isn't a way to customize and extend Canvas yet, the original fields mentioned in this issue are addressed by the `canvas_user_meta` table.
