### ISSUE TITLE
Question: Laravel 5.5

### ISSUE THREAD

**Issue by sudosammy** [cnvs/canvas#511]
Hi Todd,

Canvas is very impressive and I hope you are proud of it. I see that it only supports Laravel 5.8 though and since 5.5 is the LTS release I'm really hoping to deploy on this version.

Are you able to give me an indication of the effort required to patch Canvas to operate on 5.5?

Cheers.

**Comment by austintoddj** [comment]
Haven't given it a try on 5.5 with the latest version, but let me give it a go later today and I'll give you an update.

**Comment by sudosammy** [comment]
Thanks Todd, looking forward to hearing your thoughts.

**Comment by austintoddj** [comment]
Added support for Laravel LTS with [v4.2.5](https://github.com/cnvs/canvas/releases/tag/v4.2.5)
