### ISSUE TITLE
Autosave is available in the platform?

### ISSUE THREAD

**Issue by barbosa89** [cnvs/canvas#514]
Hi guys, 

I am testing the canvas blog package but autosave is not working, there is some configuration to enable it? Only save and publish.

Thanks

**Comment by austintoddj** [comment]
It's not currently supported in the platform.

**Comment by barbosa89** [comment]
How can I save a draft?

**Comment by austintoddj** [comment]
When you Save/Publish, set the published date to be in the future, that will make it a draft.

Now that you bring this up, I can probably make the wording a little bit more clear. I'll get it added in an upcoming release.

**Comment by barbosa89** [comment]
Great, thanks @austintoddj
