### ISSUE TITLE
Does this package support multilingual content?

### ISSUE THREAD

**Issue by mabasic** [cnvs/canvas#517]

**Comment by austintoddj** [comment]
Yes it does. The following translations are supported:

- Arabic
- Chinese (Simplified)
- German
- English
- Spanish
- French
- Hindi
- Portugese (Brazilian)
- Russian

**Comment by mabasic** [comment]
You are talking about package localization or content translations?

I can't find a way to have content in multiple languages.

**Comment by austintoddj** [comment]
I was referring to package localization. The content itself won't be translated.

**Comment by mabasic** [comment]
Do you plan on implementing this feature? I would like to help with this if needed. 

I have recently created a multilingual laravel blog admin ui with bootstrap 4 and then I saw this package. 

This package looks much nicer, but since it does not support multilingual content I can't use it.

**Comment by austintoddj** [comment]
I'm absolutely open to reviewing a PR for this if you'd like to submit one, I'd love to see what you come up with.

Canvas was first released in early 2016. Each major version has been a re-write. The latest `v4.0.0` took design inspiration from Wink and adopted relevant pieces of code, modified it, and catered it to what we have now.

**Comment by urtzi88** [comment]
Hi @mabasic I came across something similar and this is how I have managed it:

I've defined tags referencing languages ('es', 'en', 'fr'...) and then created a new Post model that extends the original \Canvas\Post one and have included the following scopes in:


~~~~
// This only fetches the posts with the tag of the current locale
public function scopeOfLanguage($query)
{
    return $query->whereHas('tags', function ($q) {
        $q->where('slug', App::getLocale());
    });
}

// And this removes the language tags from the loaded tags
public function scopeWithTags($query)
{
    return $query->with(['tags' => function ($q) {
        $q->whereNotIn('slug', self::LANGUAGES);
    }]);
}
~~~~

Then in the BlogController (based on the one provided), I fetch the posts using:

~~~~
$posts = Post::with('topic')->withTags()->ofLanguage()->published()->get();
~~~~

I hope this helps.

**Comment by mabasic** [comment]
@urtzi88 Aha, I see. You used tags to mark content for specific language and then you removed those tags before displaying the posts. Clever, but you still have, if I am not mistaken, tag names on one language and you would have to perform some magic to properly seo optimize the post pages later.

@austintoddj I will give it a go and let you know of my progress with this. I'm fairly new with Vue and will need help there, but the backend stuff (database, models, routes) I can handle.

**Comment by austintoddj** [comment]
Closing this out. I'll take a look at a PR if you submit one.

**Comment by Itemshopp** [comment]
@mabasic Have you finally found out a way to implement Localization on content ?

**Comment by mabasic** [comment]
> @mabasic Have you finally found out a way to implement Localization on content ? 

No, I have abandoned this attempt.
