### ISSUE TITLE
Is it possible to add multiple topics per post?

### ISSUE THREAD

**Issue by urtzi88** [cnvs/canvas#518]
Hi there,

First of all, great work with this package!

I was wondering if it was possible to add multiple topics for each posts. I see that topics and posts have a many to many relationship, so theoretically it should be possible, but the topic selection component only lets me choose one.

Is there anything I can do to change it? or did I miss any config step?

Thanks a lot in advance ;)

**Comment by austintoddj** [comment]
You didn't miss anything. You're right in noticing that, the relationship is something I can modify to make it a bit clearer. 

The idea with Topics is that they categorize posts differently than Tags.  Since topics have a more general scope, posts will only fall under one topic if any.

**Comment by urtzi88** [comment]
Thanks for the quick response. In that case I suppose for what I want I better use tags instead.

Thanks again!
