### ISSUE TITLE
Error 500. no 'host' index

### ISSUE THREAD

**Issue by robertgarrigos** [cnvs/canvas#533]
I was having this error. it said there was no 'host' index and it was pointing to this line:
https://github.com/cnvs/canvas/blob/502fd6883dff368025c53f7c03a67c78721a4d73/src/Post.php#L219

The problem was that `$item->referer` can be also empty thus still giving false to the condition and trying to print the key 'host', which doesn't exist.

I'll file a PR.

**Comment by robertgarrigos** [comment]
Done: https://github.com/cnvs/canvas/pull/534

**Comment by austintoddj** [comment]
Fixed with [v4.2.7](https://github.com/cnvs/canvas/releases/tag/v4.2.7)
