### ISSUE TITLE
Feature suggestion: Add support for video upload

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#540]
See this PR here:
https://github.com/writingink/wink/pull/194

**Comment by ilicmarko** [comment]
I can expend more on this, like:

* using `PHP-FFMpeg` to generate a thumbnail (poster),
* support uploading multiple formats (not really needed),
* add `type` attribute to source
* additional checks that is actually a video?

**Comment by austintoddj** [comment]
So I didn't add Video uploads yet, but the enhancements introduced in [v5.2](https://github.com/cnvs/canvas/blob/master/changelog.md#520-february-9-2020) would allow us to build that out in the future. 

And while I'm not going to focus on that at the moment, I did add a feature to bring this a little closer to Medium.com's functionality that is has with [embed.ly](https://embed.ly/):

<img width="1008" alt="Screen Shot 2020-02-10 at 8 18 46 AM" src="https://user-images.githubusercontent.com/8037011/74158360-8e92d880-4bdf-11ea-9710-edfe906d1ac7.png">

So if you've never checked out embed.ly, it's an amazing service that takes your URLs and gives you back  a nice embeddable response for your app. It's a paid service however, so it won't work in this package. 

The alternative that I went with was to manually parse out the video links and properly build out embeddable snippets. Labor-intensive and definitely has its shortcomings, but you can [see it for yourself here](https://github.com/cnvs/canvas/blob/master/resources/js/components/editor/EmbedVideoBlot.js#L66).

My goal is to flesh out that class and add lots more providers, in time.
