### ISSUE TITLE
undefined 'host' key when listing stats

### ISSUE THREAD

**Issue by robertgarrigos** [cnvs/canvas#545]
I found this error again when the referer is not either null or empty but a not well-formed URL. I found some malicious code in the rerefer column of the canvas_views table which triggered this error. Provably, in the first place, we should avoid writing that code to the database. However, I will file a PR to avoid getting the host of a not well-formed URL.

**Comment by robertgarrigos** [comment]
This is it https://github.com/cnvs/canvas/pull/546

**Comment by austintoddj** [comment]
Fixed with https://github.com/cnvs/canvas/commit/1b3ad47c671d53bc18222d59a62266c3bcb57d00
