### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#549]
Canvas 4.2.7 does not support Laravel 6.0 as it requires the specific Laravel 5.8 package. With that in mind, I slightly modified composer.json and fixed a small bug in the View Blog/Show on my fork setappufv/canvas.

**Comment by albertoelias123** [comment]
https://github.com/setappufv/canvas/commit/b071e8ccaa27d583102c4139e311cd4d3a03e1c5

https://github.com/setappufv/canvas/commit/7840e3b636920d171156b5beb49726f29d298263

**Comment by austintoddj** [comment]
**v4.3.0** will support the latest version of Laravel. Hoping to push it out by the end of the month.
