### ISSUE TITLE
Question/Feature: Assigning Different Authors

### ISSUE THREAD

**Issue by impsart** [cnvs/canvas#550]
Hi. Great package.

Is there a way to change or assign a post to a different author? 
Currently we're populating posts but from one account and we wish to assign it to a different user. Not sure 

Thanks.

**Comment by austintoddj** [comment]
Thanks!

The package doesn't support changing authors from a UI perspective. The reason behind that is simply the idea that one author shouldn't/doesn't need to be assigning different things. Everyone writes their own content. Under the hood that means that the `auth()->user()->id` is assigned to whoever authors the post.

If you do need to change this however, it's as simple as updating the `user_id` column in the `canvas_posts` table.

**Comment by impsart** [comment]
Noted.. Thanks Austin.
