### ISSUE TITLE
Unable to install it.

### ISSUE THREAD

**Issue by montuIO** [cnvs/canvas#551]
ewarner@canvas:~/canvas$ composer require cnvs/canvas
Using version ^4.2 for cnvs/canvas
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install cnvs/canvas v4.2.7
    - Conclusion: don't install cnvs/canvas v4.2.6
    - Conclusion: don't install cnvs/canvas v4.2.5
    - Conclusion: don't install cnvs/canvas v4.2.4
    - Conclusion: don't install cnvs/canvas v4.2.3
    - Conclusion: don't install cnvs/canvas v4.2.2
    - Conclusion: don't install cnvs/canvas v4.2.1
    - Conclusion: remove laravel/framework v6.0.3
    - Installation request for cnvs/canvas ^4.2 -> satisfiable by cnvs/canvas[v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7].
    - Conclusion: don't install laravel/framework v6.0.3
    - cnvs/canvas v4.2.0 requires illuminate/support ~5.8.0 -> satisfiable by illuminate/support[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.11|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.12|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.14|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.15|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.17|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.18|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.19|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.20|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.22|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.24|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.27|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.28|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.29|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.30|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.31|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.32|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.33|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.0.3
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.0.3
    - Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by austintoddj** [comment]
Support for Laravel 6 was added in [`v4.2.8`](https://github.com/cnvs/canvas/compare/v4.2.7...v4.2.8). If you retry the installation now, what results do you get?

**Comment by austintoddj** [comment]
Closing for now, let me know if you still run into this since it should be taken care of by the above comment.
