### ISSUE TITLE
Publish the admin views

### ISSUE THREAD

**Issue by GigaMick** [cnvs/canvas#559]
I followed the directions and published the canvas views so that I can override them, however the views for the admin pages are not available to me. How can access and override these?

Thanks

**Comment by austintoddj** [comment]
Those aren't meant to be overridden since they are the core of the package. Is there something you wanted to change in there?

**Comment by markronquillo** [comment]
lets say if we want to add something to the editor like another field? or probably prefill the editor title based on a url param. Will that require us to copy the code locally and just implement the changes?

**Comment by austintoddj** [comment]
What kinds of things are you wanting to add to the editor? If it’s a viable change then feel free to detail out what you’d like or submit a PR.
