### ISSUE TITLE
Posts per user

### ISSUE THREAD

**Issue by atymic** [cnvs/canvas#572]
Currently any user logging in will see all the posts of any user (even though each post is correctly associated with the user that created it).

Is this the expected behaviour?

I'd be happy to to PR a fix if you consider it a bug, or pr a feature to add a config option so you can only see your own posts.

Thanks :)

**Comment by austintoddj** [comment]
Thanks for offering a PR! That fix will actually be included in the `v4.3` release coming up soon.

The updated controller response can be seen here: https://github.com/cnvs/canvas/blob/develop/src/Http/Controllers/PostController.php#L23

**Comment by atymic** [comment]
Oh ok, perfect. Thanks!
