### ISSUE TITLE
Drag and dropping images in the editor issue

### ISSUE THREAD

**Issue by markronquillo** [cnvs/canvas#574]
Good day,

I have an issue with the editor where if you try to drag an embedded image it copies the image instead of just moving it. 

Is this the default behavior? I tried this in vanilla quill.js it doesn't behave that way, it moves the image instead of duplicating. Thanks

<img width="1280" alt="Screen Shot 2019-11-20 at 4 48 41 PM" src="https://user-images.githubusercontent.com/1182515/69223089-a3019f00-0bb5-11ea-9017-e08e6bb698fe.png">

<img width="1280" alt="Screen Shot 2019-11-20 at 4 48 48 PM" src="https://user-images.githubusercontent.com/1182515/69223103-a85ee980-0bb5-11ea-80e4-f28c1a9ba441.png">

**Comment by austintoddj** [comment]
I haven't run into this behavior before, but let me try and replicate it to see what's going on.

**Comment by markronquillo** [comment]
I think it has something to do with contenteditable being false. Anyway if you remove that it works as intended. Thanks

**Comment by austintoddj** [comment]
Thanks for the heads up @markronquillo
