### ISSUE TITLE
I have some questions.

### ISSUE THREAD

**Issue by vimalmistry** [cnvs/canvas#588]
I want to build blog site and canvas is just perfect for me. But I have some question and didn't find any answer or document or something.

-  Is there any document?
-  How to switch theme like dark mode in suggested by canvas.io site.
-  Is there any search option for posts?
-  Is there filter for post because I have to give right for some user to post?
- How to add editor functionality like List and table?

**Comment by austintoddj** [comment]
Great questions.

- Not sure about the first one, about a "document"?

- To utilize dark mode, simply un-comment the `Canvas::night()` method in the `CanvasServiceProvider` [just like the readme says](https://github.com/cnvs/canvas#options)

- You can search posts by using the icon in the upper-right corner of the posts screen:
<img width="951" alt="Screen Shot 2019-12-23 at 6 15 16 AM" src="https://user-images.githubusercontent.com/8037011/71357532-ad63df80-254b-11ea-9d4d-41c5b06e2915.png">

- For the third question, are you asking if you want to restrict user access to Canvas on your site?

- You can paste HTML markup into the editor here like this:
<img width="851" alt="Screen Shot 2019-12-23 at 6 17 34 AM" src="https://user-images.githubusercontent.com/8037011/71357623-f3b93e80-254b-11ea-8284-688b4480bdca.png">
