### ISSUE TITLE
Suggestion:Is better to it can keep the space and Tab of the article

### ISSUE THREAD

**Issue by airy6** [cnvs/canvas#599]
This is a beautiful blog. But is better to it can keep the space and TAB of the beginning of the article, it is better to center the picture👍

**Comment by austintoddj** [comment]
I'm sorry, not understanding the question. Could you re-phrase it?

**Comment by airy6** [comment]
I'm sorry, English is not my native language, I mean, I think it would be better if it could keep the space at the beginning of the paragraph and center the picture

**Comment by airy6** [comment]
My english is not very good, hope you can understand😃

**Comment by austintoddj** [comment]
No problem at all.

Are you talking about the Featured Image? Or images inside of the post?

**Comment by airy6** [comment]
Yes, picture in post

**Comment by austintoddj** [comment]
The embedded images in a post are centered within the content. If you want to see a different option or configuration feel free to submit a pull request!

**Comment by airy6** [comment]
Thank you. It's great!
