### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#602]
@austintoddj 
This repository is wonderful!
I would like to know how I can contribute to the development of the project? Have you considered the next features?
Does this project accept donation or sponsorship?

**Comment by austintoddj** [comment]
Thanks for the kind words @albertoelias123!

If you click the **Sponsor** button above, you'll see all of the sponsorship opportunities available. 

As far as contributing, if you want to jump in on [any of the issues](https://github.com/cnvs/canvas/issues) and add any helpful guidance for people that have had trouble that would be a great start! At the same time, if you do think of features or things that you'd like to see this package have, feel free to create new issues and I'll see what it'll take to add them as new features.
