### ISSUE TITLE
Question: Canvas Integration for Existing Admin Back-end

### ISSUE THREAD

**Issue by easterneas** [cnvs/canvas#604]
I'm not sure if it's already mentioned or not in the readme, but I think it's worth to be mentioned here.

I already built the administration back-end, and also made the basic blogging feature within it. Now if I want to migrate to Canvas, I would expect that there will be 2 back-ends (one for my administration site, and another one for Canvas).

Is there any way to integrate Canvas back-end into my existing administration sites without using iframe?

Thanks :)

**Comment by yoeriboven** [comment]
If your existing backend uses the Laravel authentication, you can just use it.

Current backend on `url.com/admin`? Then you can change the `path` in the config so they are both on the `admin` prefix.
Add a link from your current admin to the canvas page and you're done.

**Comment by austintoddj** [comment]
What @yoeriboven is correct. While you're not able to make the backend 'look' like your current Admin section, it can be accessed and protected by the same middleware and authentication that your current setup has.

**Comment by iatroshchenko** [comment]
What about back to  website button? Is it implemented somewhere? Or how can I add this right now?

**Comment by yoeriboven** [comment]
@iatroshchenko You could fork this package and import that into your project. Then just add the button to your 'own' admin panel and build the Vue files.

**Comment by austintoddj** [comment]
The `Visit Site` button used to exist, but was removed when a frontend was no longer bundled with Canvas. 

By only including the tools necessary to write and publish posts, everyone is free to design their frontend as they see fit or with whatever style they're integrating into. With this de-coupling, Canvas no longer "knows" about the frontend, and there isn't currently a system in place where you can pass your defined post/tag/topic routes to the package.
