### ISSUE TITLE
Unsplash Rate Limiting

### ISSUE THREAD

**Issue by mikerockett** [cnvs/canvas#605]
The search box on the Unsplash popup currently has no strategy to avoid API rate limiting on Unsplash. As a result, I get a ton of 403s, which breaks the results – they don’t update and land up remaining as they are.

Could a one-second debounce be added here?

Fantastic package – using this for my new site and blog, and it's working super-well. :-)

**Comment by austintoddj** [comment]
Really glad to hear that @mikerockett! Yes, I'll add a debounce to that. Hoping to get the next release out either this week or next.

**Comment by mikerockett** [comment]
Awesome stuff, thanks!

**Comment by austintoddj** [comment]
Added in **v5.1.0**

- [Upgrade Guide](https://github.com/cnvs/canvas/blob/master/upgrade.md#upgrading-to-510-from-50)
- [Changelog](https://github.com/cnvs/canvas/blob/master/changelog.md#510-january-22-2020)

**Comment by mikerockett** [comment]
Thanks Austin! 😃
