### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#609]
Hi, I'm trying to work on some improvements for Canvas and I'm following CONTRIBUTING, but I'm having some doubts.
I believe the command `php artisan:migrate` is actually `php artisan migrate`. Right?
I was unable to use the --data option, present in version 4.x. Because of this, I chose to use the Factorys, for that I modified the CanvasProvider boot and added the Canvas Factories, I am also making a Seeder that runs some factories to facilitate development.
In CanvasServiceProvides, in some methods such as registerPublishing, there is an IF that I did not understand your purpose, could you explain? (https://github.com/cnvs/canvas/blob/4aeaa2eb5c2b421ddecb878a64cd0c160413fc17/src/CanvasServiceProvider.php#L104)

Can I do a PR, with the corrections and improvements I'm making?

**Comment by albertoelias123** [comment]
Another issue I didn't understand, each post can have 0 to N TAGs and 0 to 1 TOPIC. But the relationship between Post and Topic supports the relationship 0 to N, wouldn't it be more interesting to remove the `canvas_posts_topics` table and add an attribute (nullable) to the post table to identify the referring topic?

**Comment by austintoddj** [comment]
Although the relationship is set up as such, the idea is that a Topic is a category, a page, a series, or whatever you'd like to call it. Tags can merely attach to anything. So even though the relationship looks the same, the application code supports this idea. So I'd like to leave the migrations alone for now and keep this structure.

And you're correct in the first comment, it's a mistake in the docs. Submit a PR for it and I'll get it merged in.

**Comment by austintoddj** [comment]
Fixed in [v5.2.0](https://github.com/cnvs/canvas/releases/tag/v5.2.0)
