### ISSUE TITLE
Problem with canonical link

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#610]
If the user fills in the Canonical Link with any text that is not a valid URL, we encounter an error similar to the one found below.

https://github.com/cnvs/canvas/blob/4aeaa2eb5c2b421ddecb878a64cd0c160413fc17/resources/stubs/views/blog/show.stub#L82-L90

![image](https://user-images.githubusercontent.com/41304037/73131441-c7c92700-3fe9-11ea-9b4e-2170f240828b.png)

**Comment by austintoddj** [comment]
Good catch. Go ahead and submit a PR for this and I'll get it merged in.
