### ISSUE TITLE
How to change UI / Redirections 

### ISSUE THREAD

**Issue by bardhkrasniqi** [cnvs/canvas#619]
Hi

I'm trying to make some changes on ui and redirections but i can't see pages being updated.
Should i run yarn or something else to compile again vue files? 

Any ideas?

**Comment by austintoddj** [comment]
Good question @bardhkrasniqi. If you check out [the contributing guide here](https://github.com/cnvs/canvas/blob/master/.github/CONTRIBUTING.md), you'll see a step-by-step process for compiling assets in a dev environment. Let me know if you have any questions or issues with it!

**Comment by bardhkrasniqi** [comment]
Thanks for the help.

When i make changes on `*.blade.php` it's working but i'm still having issue with `*.vue` files i don't see changes.  
For example i want to change `Logout` to `Home` on `PageHeader.vue` but i don't see changes

I don't know if i'm missing something...

**Comment by austintoddj** [comment]
What you're seeing is correct. The blade templates that were generated during the setup are just a nice starting point for how you want to customize the frontend aspect of your application. The Vue files are part of the package, so they're not editable by you. 

Does that make sense?
