### ISSUE TITLE
Linking Issue

### ISSUE THREAD

**Issue by jonbaldie** [cnvs/canvas#624]
Fresh install today, if I try to add a link to some text, it replaces the entire line with the text value of the link I entered. No errors reported in the console.

![2020-02-09 17 32 43](https://user-images.githubusercontent.com/8376953/74106877-6e710400-4b62-11ea-8cdb-eb0347f44904.gif)

Made no changes to JavaScript files or Blade views, and replayed `npm install && npm run dev` to make sure I wasn't going wrong somewhere.

**Comment by jonbaldie** [comment]
Got paranoid that I'd changed something by accident, so I did another fresh install using the directions in the readme file, and got the same results.

**Comment by jonbaldie** [comment]
If it helps, confirmed working as expected (link works without replacing text) on an old version I'm using for another site, v5.0.3.

**Comment by austintoddj** [comment]
Thanks for catching this @jonbaldie, and for the really helpful gif.

I’ll take a look at this shortly.

**Comment by jonbaldie** [comment]
Thanks for the quick response @austintoddj ✌️
