### ISSUE TITLE
Bugs Found

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#625]
This Middleware was renamed to Session, but in the stub files it remains with the old nomenclature.
That is, when using the `canvas:setup` command, the wrong Middleware name is used.

https://github.com/cnvs/canvas/blob/deada10d1d9c53ded0537147d64a46f7f3354421/resources/stubs/routes.stub#L4
<br/>
In addition, I also encountered another problem, after correcting the Middleware name and trying to access a specific Post by the slug. Below is the image:
![image](https://user-images.githubusercontent.com/41304037/74114594-c4a56d80-4b89-11ea-94c8-11e2b818a96f.png)

To solve the problem I changed the lines below. 
https://github.com/cnvs/canvas/blob/deada10d1d9c53ded0537147d64a46f7f3354421/src/Listeners/CaptureVisit.php#L43-L48
Leaving like this:
https://github.com/albertoelias123/canvas/blob/167f51fbf4816e427548f5f72df91c6f00570ca8/src/Listeners/CaptureVisit.php#L43-L51

I will do a PR with the corrections. I thank you for your work with Canvas! SEVERAL improvements are being implemented and we are really enjoying it. I hope I can help each time with his development.

**Comment by austintoddj** [comment]
Thanks for catching this @albertoelias123, I’ll take a look at it shortly.
