### ISSUE TITLE
CaptureVisit Bug v5.2.4

### ISSUE THREAD

**Issue by HayriCan** [cnvs/canvas#635]
When I try to access post this error come off.

![capturevisit](https://user-images.githubusercontent.com/17090831/75139907-e7459380-56fe-11ea-9682-080d8abd3448.PNG)

**Comment by austintoddj** [comment]
@HayriCan What version of PHP are you running?

**Comment by HayriCan** [comment]
On PHP 7.4 I got this error. After I reduced to 7.2 and it works now.

**Comment by austintoddj** [comment]
Fixed in https://github.com/cnvs/canvas/releases/tag/v5.2.5
