### ISSUE TITLE
I got this specified key was too long on MariaDB

### ISSUE THREAD

**Issue by omandotkom** [cnvs/canvas#638]
i got this error when running canvas:install 

Migrating: 2019_12_08_000000_alter_canvas_tags_add_user_id

Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `canvas_tags` add unique `canvas_tags_slug_user_id_unique`(`slug`, `user_id`))

i think adding Schema::defaultStringLength(191) to boot() inside AppServiceProvier.php might be the solution. 

MariaDB version : 10.2.30-MariaDB - MariaDB Server

**Comment by austintoddj** [comment]
You're correct. [Per the docs](https://laravel.com/docs/6.x/migrations#creating-indexes), it looks like adding `Schema::defaultStringLength(191);` to the `boot()` method of your AppServiceProvider will fix the issue.
