### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by abishekrsrikaanth** [cnvs/canvas#645]
Could you add support to Laravel 7

**Comment by austintoddj** [comment]
Support for Laravel 7 will be coming out in the next release. Hoping to get it out before the end of the week.

**Comment by Codey-m** [comment]
Thank you!!💪💪💪

**Comment by austintoddj** [comment]
Added in [v5.3.0](https://github.com/cnvs/canvas/releases/tag/v5.3.0)
