### ISSUE TITLE
Add custom class into img tag

### ISSUE THREAD

**Issue by kenas** [cnvs/canvas#646]
First of all I would like to say thank you for your project. I really enjoy it.

Is there any possibility to add class to img tag in content/body? For example class from bootstrap like so `<img scr=”” class=”rounded float-right” alt=””> `

Thank you very much

**Comment by austintoddj** [comment]
Glad you're enjoying it! Is there a specific tag you had in mind to add? Or something specific to your application itself?

**Comment by kenas** [comment]
I am buldind a website, please have a look here https://theczechia.info/article/voluptate-velit-esse-cillum-dolore 
where I added three pictures in total. 
The first picture is featured_image so I am able to handle responsive picture by adding a class from boostrap that is fine. 

But last two pictures are added into body content as html tags (not able save with class or alt). 

I would love to have better control to add a class and alt tags and seve them into DB.

**Comment by austintoddj** [comment]
There isn't a way to add custom class tags within the editor at this time. The only way to go about adjusting images on the frontend is to target them with CSS, which should be doable. Let me know if you have any other questions about it!
