### ISSUE TITLE
The Topics synchronizes wrongly especially when two users have same topic slug

### ISSUE THREAD

**Issue by christopherokonkwo** [cnvs/canvas#647]
My case scenario is such that multiple users can have same topic name and slug but what happens  in 
`private function syncTopic($incomingTopic): array
    {
        if ($incomingTopic) {
            $topic = Topic::where('slug', $incomingTopic['slug'])->first();`

            `if (! $topic) {
                $topic = Topic::create([
                    'id' => $id = Uuid::uuid4(),
                    'name' => $incomingTopic['name'],
                    'slug' => $incomingTopic['slug'],
                    'user_id' => request()->user()->id,
                ]);
            }

            return collect((string) $topic->id)->toArray();
        } else {
            return [];
        }
    }`
Is that the user_id is not being checked for, and as such the post syncs with the first topic that matches the slug.

**Comment by christopherokonkwo** [comment]
adding a scopeforCurrentuser() method solved the problem.
ie `Topic::scopeforCurrentuser()->where('slug', $incomingTopic['slug'])->first();`

**Comment by austintoddj** [comment]
Good catch on this. It'll go out in the next release.

**Comment by austintoddj** [comment]
Fixed in [v5.3.0](https://github.com/cnvs/canvas/releases/tag/v5.3.0)
