### ISSUE TITLE
Comments and likes

### ISSUE THREAD

**Issue by Anthonynzube** [cnvs/canvas#652]
Does the canvas package for laravel support comments and likes. If it does how do I use it in a project?

**Comment by frknasir** [comment]
I am not sure what you mean by support here...but if you meant whether you could extend posts to be commentable and likable, then, YES!

How can you do that?

create two models `Comment` and `Like` with their corresponding migrations, controllers and connect them to the canvas post model using relationship. the relationships will be like 1 post to many comments, 1 post to may likes....you can look up laravel relationships for more info on that

**Comment by austintoddj** [comment]
@frknasir is right. That would be the best way to go about integrating likes/comments.
