### ISSUE TITLE
get post by date like month or year

### ISSUE THREAD

**Issue by kama003** [cnvs/canvas#659]
i want to get post by date like month or year,
please anyone can tell how can i get this i am new at laravel

**Comment by mikemand** [comment]
Hi @kama003,

Laravel has some helpful methods for the Query Builder (and Eloquent) that allow us to filter a query by month, year, day, etc. [Here's the documentation.](https://laravel.com/docs/7.x/queries#where-clauses) Scroll down to `whereDate / whereMonth / whereDay / whereYear / whereTime`.

A simple example for Posts would be:

```php
$posts = Post::whereYear('published_at', '2020')->get();
// or ->simplePaginate(10); instead of ->get(); if you want to paginate the posts.
```

```php
$posts = Post::whereMonth('published_at', '6')->get();
```

You can, of course, replace the year and month you are looking for with the request parameter (`request('year', Date::now()->year)`).

**Comment by kama003** [comment]
hi @mikemand 
what if i have month and year together
