### ISSUE TITLE
Publishing section is absent from readme

### ISSUE THREAD

**Issue by Anthonynzube** [cnvs/canvas#660]
Some weeks ago, i was able to see the section that had little code snippets in them to help me get started. Snippets like getPosts(), etc. Now i don't see them any more. how can i find them?

**Comment by austintoddj** [comment]
[Here is the link to what you're looking for](https://github.com/cnvs/canvas/tree/v5.2.5#publishing). I removed it once I created the `cnvs/studio` package that has everything already built-in.

In [Studio](https://github.com/cnvs/studio), check out the `resources/stubs/controllers` and you'll find the most up-to-date methods for grabbing the data.

**Comment by Anthonynzube** [comment]
Thank you for the link. So now i decided to use canvas, what does that mean for me? Do I need to use canvas studio, canvas or use them together? Can you explain the differences and what they do individually?

**Comment by austintoddj** [comment]
Canvas is the backend package where you can make posts/tags/topics and view the stats.

Studio is an optional frontend. The installation process is very similar to how you'd install `laravel/ui`. You aren't required to use it, it's just there to give you a fully-built frontend right out-of-the-box if you don't want to create your own.

You can absolutely use them together. And if you choose to not use Studio and just roll with Canvas, that's fine too. 

But [give the installation](https://github.com/cnvs/studio#installation) a try and let me know what you think!

**Comment by Anthonynzube** [comment]
I'll definitely do that and get back to you. Thanks for your help.
