### ISSUE TITLE
wrong language in logs

### ISSUE THREAD

**Issue by robertgarrigos** [cnvs/canvas#662]
In https://github.com/cnvs/canvas/releases/tag/v5.3.0 the language updated is Catalan, not spanish. ;-) Thanks!

**Comment by robertgarrigos** [comment]
![Release_v5_3_0_·_cnvs_canvas](https://user-images.githubusercontent.com/105581/76617043-aedaed80-6525-11ea-8882-a39ac39609aa.jpg)

This is linked to the update of the Catalan file

**Comment by austintoddj** [comment]
Good catch, thanks! Fixed now.
