### ISSUE TITLE
Adding styles to the post editor

### ISSUE THREAD

**Issue by Anthonynzube** [cnvs/canvas#663]
Is it possible to style the image i choose from unsplash when creating my blog post?

When i do this 

`{!! $data['post']->body !!}`

it gives me a default look. i'll like to style the body property myself

**Comment by austintoddj** [comment]
Not at this time, no. #472 also addresses a feature request where you could specify different layouts, but it hasn't been explored further yet.

**Comment by Anthonynzube** [comment]
How about the body of the post?

**Comment by austintoddj** [comment]
Are you referring to styling these things from the frontend, or from inside Canvas?

**Comment by Anthonynzube** [comment]
From inside canvas

**Comment by austintoddj** [comment]
If you want to "style the body of the post", you can embed raw HTML, but that's really the extent of it. What are you trying to style differently?

**Comment by Anthonynzube** [comment]
I'm trying to justify the body of my blog post

**Comment by austintoddj** [comment]
There isn't a way to justify the post content at this time. The formatting bar and the embed HTML modal is the entirety of the WYSIWYG.
