### ISSUE TITLE
Share tags/topics between users

### ISSUE THREAD

**Issue by ediblemanager** [cnvs/canvas#665]
Sorry if this is logged elsewhere!

This would be useful to avoid duplicate entries or slight discrepancies in spelling with multiple users trying to create the same tag/topic.

**Comment by austintoddj** [comment]
If you and I were on the same platform and we both authored a post with the same tag/topic, and it was subsequently deleted by you or I, it would remove it for the other person as well. I don't think that's a good experience and it makes sense to manage your own content entirely.
