### ISSUE TITLE
Allow for posts to have a scope

### ISSUE THREAD

**Issue by ediblemanager** [cnvs/canvas#666]
Needs a bit of work updating the general user roles/perms: it would be good if (like WP), there could be editor type members, admin types so that posts can be reviewed by other authors.

**Comment by austintoddj** [comment]
I can see how this would be helpful in some instances, but in regards to the size/scope of Canvas in general, I don't want to introduce permissions on that level.

**Comment by ediblemanager** [comment]
This severely limits the usefulness of Canvas :(. A straightforward ability to review someone else's post is a pretty standard thing for a publishing platform that's not an individuals blog (I'm assuming Canvas leans towards the individual blog ideal, but via Laravel supports multi-user).

Thanks for the quick answer though!

**Comment by austintoddj** [comment]
I hear you. If you want to try and throw together a PR that could support this type of thing, please feel free to do that and I'd be more than happy to take a look. It's not out of the realm of possibility, but I'm just not able to throw enough time at it right now to get it up and running.

Thanks for the feedback on the project though, every little bit helps!
