### ISSUE TITLE
Use laravel scout in Post model

### ISSUE THREAD

**Issue by itsmysterybox** [cnvs/canvas#669]
I'm trying to implement full-text search to the eloquent model. I can do that on custom models. But I want to use `Searchable` trait in canvas Post.php, so that I can use full-text search. Any idea about this implementation?

**Comment by austintoddj** [comment]
I haven't tried this before, but what if you extended the `\Canvas\Post` class and added the `Searchable` trait to that new model?

**Comment by itsmysterybox** [comment]
@austintoddj I didn't think about that. That worked. Thanks!
