### ISSUE TITLE
Blank page when entering /canvas

### ISSUE THREAD

**Issue by armancodes** [cnvs/canvas#674]
I installed everything based on the documentation but when I enter `/canvas` in my project I got nothing but a black page with the title of Canvas:
![image](https://user-images.githubusercontent.com/22839699/77235905-79926780-6bd7-11ea-9701-807478ed5ac4.png)
This is hosted on Xampp on Windows 10

**Comment by austintoddj** [comment]
Are there any console errors?

**Comment by armancodes** [comment]
I get these errors:
![image](https://user-images.githubusercontent.com/22839699/77236342-4b168b80-6bdb-11ea-9e67-aa5289884410.png)

I ran `npm install` and npm run dev` before

**Comment by armancodes** [comment]
As far as I run this project with Xampp (a LAMP stack). I have to put my different projects in different directories.
The app.js and app.css files are being read from the main directory `localhost` so it doesn't consider 'localhost/o/blog/public` and it doesn't work but when I use `php artisan serve` it makes `127.0.0.1:8000` available so it's the main root and it works.
It would be better if you could make the application find these files through the `APP_URL` specified in the .env file, so no one would get this error.

**Comment by austintoddj** [comment]
Glad you got it fixed!
