### ISSUE TITLE
Support Webp Upload

### ISSUE THREAD

**Issue by willyw2k** [cnvs/canvas#676]
Please Support Webp Images Format

**Comment by robertgarrigos** [comment]
Hey, this is great, but how is it supposed to give a jpeg alternative for browser which don't support webp?

**Comment by willyw2k** [comment]
> Hey, this is great, but how is it supposed to give a jpeg alternative for browser which don't support webp?
u can use html5 picture tag

example : 
<picture>
  <source srcset="img/awesomeWebPImage.webp" type="image/webp">
  <source srcset="img/creakyOldJPEG.jpg" type="image/jpeg"> 
  <img src="img/creakyOldJPEG.jpg" alt="Alt Text!">
</picture>

**Comment by robertgarrigos** [comment]
I'm aware of the html5 picture tag. Problem is: you can now upload a webp image as featured image, but there is no way to upload a jpeg alternative for that particular web image.

**Comment by willyw2k** [comment]
then u can use images cdn like shortpixel.io or imageskit.io for serve webp if browser supported

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by robertgarrigos** [comment]
Thanks. This is interesting. I'll take a look. BTW: imagekit.io and shortpixel.com ;-)
