### ISSUE TITLE
Canvas Studio for Front-end " Studio is not defined" error

### ISSUE THREAD

**Issue by Mint-developer** [cnvs/canvas#677]
I installed canvas studio as a front-end in the same project directory as the canvas admin portal is. When I ran "npm run dev" I got a weird error saying " Studio is not defined" in the browser console.

Please help me.

**Comment by austintoddj** [comment]
So you've got a Laravel app set up, and both Canvas and Studio are dependencies that were installed in the project, correct?

**Comment by Mint-developer** [comment]
@austintoddj thank you so much for replying. Actually I've set up Canvas for writing content. Now I want to set up canvas studio for front-end. I went through the official documentation and installed Canvas Studio in the same project as the Canvas is. The install went fine but I get "Studio is not defined" error. I am using vue js for the front-end. 

After getting the error, I did a fresh installation of both Laravel 7 and Canvas. Now I am using vue js to develop the front-end (not using Canvas Studio anymore). Could you please guide me how should I connect my vue js components with Canvas. Should I create my own APIs or should I consume the APIs provided by Canvas which are used in the Canvas backend itself.

**Comment by austintoddj** [comment]
Hm interesting, not sure why it would be undefined at that point.

If you take a look at [cnvs/studio](https://github.com/cnvs/studio), it's set up as a Vue app and has all the consumable API points you'd need built out already. Take a look at the Controllers and you'll get a good idea of how to grab the content.

**Comment by Mint-developer** [comment]
@austintoddj your help is much appreciated! thanks

**Comment by austintoddj** [comment]
Were you able to resolve this @Mint-developer?

**Comment by austintoddj** [comment]
Appreciate insight from anyone else that has run into this. Unable to reproduce.

**Comment by austintoddj** [comment]
Fixed in https://github.com/cnvs/studio/releases/tag/v1.0.1
