### ISSUE TITLE
[Feature] Publish/Draft dropdown to tabs

### ISSUE THREAD

**Issue by mikemand** [cnvs/canvas#679]
Hi @austintoddj,

Do you have plans for more than just the two options in the dropdown on the Posts page? <img width="152" alt="Screen Shot 2020-03-27 at 1 30 38 PM" src="https://user-images.githubusercontent.com/745184/77793136-2f721180-702f-11ea-9b67-bc6545c71e9f.png">

If not, would it be possible to change this to side-by-side buttons or tabs or whatever that UI element is called? My users keep asking where the draft posts are and I have to keep telling them (and then they go "oh, right").

**Comment by austintoddj** [comment]
I didn't have any plans at the moment in changing that, but if there's enough support or need for it I wouldn't mind exploring options.
