### ISSUE TITLE
Vapor Support

### ISSUE THREAD

**Issue by mdpoulter** [cnvs/canvas#680]
Thanks for the great package! I just have one query though:

It doesn't appear to from the documentation, but does Canvas support file uploads using Laravel Vapor? Specifically, I'm referring to streaming the files to S3 from the frontend. The Vapor documentation for this can be found here: https://docs.vapor.build/1.0/resources/storage.html#file-uploads

Thanks!

**Comment by austintoddj** [comment]
Glad you're finding the package useful!

I haven't dug into compatibility with Vapor before, but I'll take a look!
