### ISSUE TITLE
Everytime I merge new changes its asking me to publish canvas 

### ISSUE THREAD

**Issue by heyaj19** [cnvs/canvas#699]

**Comment by austintoddj** [comment]
Since this issue has no description, it's a bit difficult to understand the context.

Could you be a bit more specific on what's happening?

**Comment by heyaj19** [comment]
Oops sorry I got side tracked and must have submitted the bug. So installed the canvas on my dev machine I promoted it to my prod environment. I actually had to install it on prod as composer automatically did not pick it up originally. Rather I had to do a full composer update as it didnt pick up other packages as well.

I made more changes on my DEV environment and on merging codes to production and deploying it - I had to re publish canvas again. Not sure why this is happening?

**Comment by austintoddj** [comment]
I've released 3 versions in the last 2 weeks, perhaps you just grabbed an updated version, in which case it would make sense that you'd need to re-publish the assets.

**Comment by heyaj19** [comment]
I pushed it to production yesterday - my composer is set to grab the updated patch in the version. And then I pushed an update on the app as well yesterday, I had to publish it again. 

Ill keep an eye out. I did find a few issues - ill create a separate bug for those

**Comment by austintoddj** [comment]
Ok, sounds good. Well let me know if you find anything concrete that I can go on and I'll take a look at it right away.
