### ISSUE TITLE
On changing username or uploading a profile picture the form exists even when there is an error

### ISSUE THREAD

**Issue by heyaj19** [cnvs/canvas#700]
I had to use dev tools to figure out why my the new username was not saving on the general settings app and the image although looks like its updated also wasn't saving. That can be attributed to the username not saving. 

A good idea for UI might be to confirm that the picture has been uploaded and then saved. For the username it would be good to see the error before it exists to the screen.

**Comment by austintoddj** [comment]
Could you list out the steps you took to hit this error?
