### ISSUE TITLE
Class 'Locale' not found 

### ISSUE THREAD

**Issue by graigDev** [cnvs/canvas#703]
This error is triggered when you want to access the route **/canvas** after connection.

**Comment by graigDev** [comment]
Error Line 63

solution: $translations->put($locale, Str::ucfirst($locale, $locale));

Delete class Locale. Thanks

**Comment by hadidadkhah** [comment]
For linux just install php7.0-intl base on your php version.
`sudo apt-get install php7.5-intl`

**Comment by austintoddj** [comment]
I pushed out the Localization feature without thinking that the PHP `intl` extension was necessary. Currently looking into Carbon to see if it could provide similar functionality without having the extension required.

**Comment by austintoddj** [comment]
Fixed in https://github.com/cnvs/canvas/releases/tag/v5.3.8

**Comment by hadidadkhah** [comment]
composer update will generate this error:

In Cache.php line 231:
                                                                          
  hash_file(): read of 8192 bytes failed with errno=5 Input/output error
