### ISSUE TITLE
Publishing doc removed

### ISSUE THREAD

**Issue by dgillier** [cnvs/canvas#706]
Hello,
Any reason why the Publishing part of the readme (was there early Feb) disappear ?
Deprecated API coming up , or else ?

Thanks,
Denis

**Comment by austintoddj** [comment]
The readme does have some rolling changes, is there a part of it you were looking for or had a question about? I can probably point you in the right direction.

**Comment by dgillier** [comment]
Thanks for the “create” bug solving !
Found the old publishing doc (in the feb read me version), was needing the publishing part to do my own frontend. 

Take care, Denis

**Comment by austintoddj** [comment]
No problem! As far as the publishing section, that did get removed to favor Studio as the frontend instead. Let me know if you have any questions about it:

https://github.com/cnvs/canvas#frontend

**Comment by dgillier** [comment]
I’ve go two more problems regarding images, should I use post them with github  ?

- Unsplash not working (having a correct public API key in the canvas.php file)
- The “Posts” list view does not display the feature image (I uploaded one, and the file was correctly uploaded into storage/public/canvas/images).

Denis
