### ISSUE TITLE
New post isn't working

### ISSUE THREAD

**Issue by InvokerMaster** [cnvs/canvas#708]
When I click `New Post`, it redirects to /create but console says api/posts/create is not found.
Does anyone have idea on this?

**Comment by austintoddj** [comment]
Just fixed in the [v5.3.9](https://github.com/cnvs/canvas/releases/tag/v5.3.9) release. Had broken the controller. Go ahead and run a `composer update` and `php artisan canvas:publish`. Should work for you now.

**Comment by InvokerMaster** [comment]
Great thank you! It's working now.
