### ISSUE TITLE
Unsplash not working

### ISSUE THREAD

**Issue by dgillier** [cnvs/canvas#710]
I entered a correct public key into canvas.php and the unsplash UI is not appearing in the image modal.

**Comment by austintoddj** [comment]
When you entered it into the config file, did you clear the application cache?

It's a little better practice to set those in the .env file. So try setting the `CANVAS_UNSPLASH_ACCESS_KEY` in there and let me know if you see any difference.

Also, are you seeing any console errors when you're creating the post?

**Comment by dgillier** [comment]
No, not working for me:
No errors in the browser console.
Did an app clear cache
Tried also with the key into the .env file (tried with and without ")

**Comment by dgillier** [comment]
Finally worked with Variable in the .env file...
Don't know what was wrong, but working now ;)
