### ISSUE TITLE
Nicer default Slug Name...

### ISSUE THREAD

**Issue by dgillier** [cnvs/canvas#711]
It would be nice to have the default slug name being based on the title name (like it's done when using the refresh icon) instead of the kind of id default one which always need to be changed...

**Comment by austintoddj** [comment]
I can see what you're saying here, but since there is an option to Sync the slug after it's created, I'm going to leave it at that for the time being.

**Comment by dgillier** [comment]
No, problem, not a big deal ;)
Thanks, 
Denis
