### ISSUE TITLE
How to use Canvas Quill Editor in my Bootstrap / HTML & CSS

### ISSUE THREAD

**Issue by channaveer** [cnvs/canvas#718]
Hi, Thank you very very much for getting such an awesome project to the community out there. Since I don't have any knowledge on VueJs I cant extract Quill Js editor CSS and JS to my custom project. I am really attached to the Canvas editor and don't wanna miss it.

Can you please guide me on how to implement the same with Bootstrap 3 or Bootstrap4 or HTML & CSS.

It will really help me a lot and  I hope many community users will be benefited with this.

**Comment by channaveer** [comment]
I want to know how to add that small + symbol and control everything based on that.

**Comment by austintoddj** [comment]
Glad you're getting some use out of it!

I'd hit up this article if I were you: https://quilljs.com/guides/cloning-medium-with-parchment/

It gives a nice, in-depth tutorial to do what you're looking to do.

**Comment by channaveer** [comment]
Thank you very much for the link. Looks 
like awesome article.
