### ISSUE TITLE
Standalone installation

### ISSUE THREAD

**Issue by hide-me** [cnvs/canvas#726]
If you make a **standalone release**, with the installation of Canvas without using Composer (which is very convenient and important for cheap hosting). I make a quality translation of Canvas into Russian 🇷🇺

**Comment by austintoddj** [comment]
Are you saying it's difficult to get it up and running? What would make it easer?

If you see any poor translations in the `resources/lang/ru/app.php` file, feel free to submit a quick PR and I'll get it merged in!

**Comment by hide-me** [comment]
No, it's not difficult in general. But, many users usually haven't any experience with Composer. Try to [install this flat-file micro CMS](https://www.bludit.com/) (for example) in your test server/hosting. You will see: the installation takes only a few clicks. Download the zip and unpack it in your host, then _click next next next type admin password and JOB DONE_.

**Comment by hide-me** [comment]
I just see how you promote your system as **super easy to use and manage**. It would be great if users could install it without special skills and knowledge, without guides and tips.

Like I wrote: next, next, type password... and the job is done!

**Comment by austintoddj** [comment]
I see what you're saying. Let me put some thought into that and see if I can find a good solution for it here.

**Comment by austintoddj** [comment]
Gave it some thought and decided that I may go and create some sort of installer someday, but it's not on the roadmap at this time. Thanks for the suggestion though @hide-me!
