### ISSUE TITLE
Error while database migrating via PostgreSQL

### ISSUE THREAD

**Issue by BuyOwnEx** [cnvs/canvas#728]
Migrating: 2020_04_10_000000_alter_canvas_tables_user_id_column_type

   Illuminate\Database\QueryException  : SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "user_id" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING user_id::bigint". (SQL: ALTER TABLE canvas_user_meta ALTER user_id TYPE BIGINT)

  at C:\OSPanel\domains\buyownex.main\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "user_id" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING user_id::bigint".")
      C:\OSPanel\domains\buyownex.main\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:129

**Comment by BuyOwnEx** [comment]
via MySQL migrating was OK

**Comment by austintoddj** [comment]
Thanks for bringing this up. If you've got existing data in PostgreSQL, you'll need to alter the `user_id` field types from a `varchar` to an `int` on these tables:

- `canvas_user_meta`
- `canvas_posts`
- `canvas_tags`
- `canvas_topics`

Apparently PostgreSQL has a hard time altering types like this, so once you've updated the fields, the migration should run properly.

**Comment by BuyOwnEx** [comment]
Yes, I`m already do this. But this error must be fixed. Studio was installed from scratch 
Or delete from requirements about FOUR supported databases by Laravel

**Comment by austintoddj** [comment]
Up to this point however, Canvas was integrating with your app correctly via PostgreSQL, right? 

I agree this was an unforeseen issue. So, just so I understand fully, you can't get this to work with PostgreSQL as a fresh install of Canvas/Studio?

I'm tossing around the idea of cleaning up the migrations on the next release. The upgrade path might be a little more involved, but it would save the effort of having to alter tables and columns with all the migrations at this point.

**Comment by BuyOwnEx** [comment]
> I agree this was an unforeseen issue. So, just so I understand fully, you can't get this to work with PostgreSQL as a fresh install of Canvas/Studio?

Yes. Sorry, that this issue was in cnvs/canvas. It might be in Canvas/Studio repository, I guess

**Comment by austintoddj** [comment]
Not a problem, appreciate the info, it makes the project better! Making some adjustments for the next release, let me know if you continue to run into issues or anything else pops up.
