### ISSUE TITLE
JSON.parse() console error

### ISSUE THREAD

**Issue by kama003** [cnvs/canvas#748]
![image](https://user-images.githubusercontent.com/45000219/82116454-9e462e00-9787-11ea-915c-f22fb4de12bd.png)
Please help me

**Comment by austintoddj** [comment]
Are you on the latest version? Or a specific branch?

**Comment by kama003** [comment]
> n the latest version

yes i am on latest version

**Comment by austintoddj** [comment]
That error would usually come from a locale issue. What do you currently have set in your `config/app.php` locale variable?

**Comment by kama003** [comment]
`config/app.php` locale variable are same as before i haven't touched that file

**Comment by austintoddj** [comment]
Another thing I'm seeing in the console is that you're getting a 404 on `api/posts`. In a browser window, can you hit the api directly and see if you get results like these here?
<img width="779" alt="Screen Shot 2020-05-17 at 8 31 52 AM" src="https://user-images.githubusercontent.com/8037011/82148277-ecefd880-9818-11ea-9200-a4f63982d11a.png">

**Comment by kama003** [comment]
![image](https://user-images.githubusercontent.com/45000219/82159068-6afbc000-98a9-11ea-96b0-c2962a44eea6.png)

this is what is got

**Comment by kama003** [comment]
Thank you so much 
you can close this issue
