### ISSUE TITLE
Search Function Tests

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#75]
PHPUnit tests should be written to test the search bar and its results in the application.

Example:
A user visits any page in the backend, clicks the `Search` icon in the top bar, and types `example`.
The user taken to the search results page and sees `Search Results for example`.

**Comment by RDelorier** [comment]
If you attempt to use the search without indexing posts first then you will see a PDOException, It would be nice to default to a simple query search if posts have not been indexed. What do you think about having a `where ... like '%term%'` as a fallback @austintoddj

**Comment by RDelorier** [comment]
Looks like it's pretty ingrained now, nevermind 💤

**Comment by austintoddj** [comment]
@RDelorier Have you experienced an issue with this?

**Comment by RDelorier** [comment]
Yes, but since the app requires TNTSearch I guess it makes more sense just to handle the issue when the exception occurs.

**Comment by austintoddj** [comment]
@RDelorier Do you think this is something I need to dig more into, or should I close this out?

**Comment by austintoddj** [comment]
@RDelorier So I'm trying to write some tests for this feature.

Basically, the process I'm trying to run is:

The database is set up for the application.
The command `canvas:index` is run.
The user logs in.
The user clicks the search icon and the bar pops open. 
The user inputs some text.
The user hits `return` since there is no submit button.
The page is redirected and the text that was searched for shows up on the following page.

Getting a little stuck. Any chance you want to take a look at it?

**Comment by RDelorier** [comment]
Hey Todd, I'm out of town without wifi 😭 until Monday but I'll take a look next week.

**Comment by austintoddj** [comment]
Sounds good @RDelorier! Sorry to hear it's a 'no wifi weekend'! 😂
