### ISSUE TITLE
Published posts not showing up on Studio

### ISSUE THREAD

**Issue by richard457** [cnvs/canvas#753]
Instead, I see this You have no published posts, isn't the expectation to see the published posts as a visiting user of the blog? please help me understand.

**Comment by austintoddj** [comment]
From the database, can you verify that the posts `published_at` is correct? Perhaps this is a locale/timezone issue.

**Comment by austintoddj** [comment]
If you could go ahead and open an [issue in Studio](https://github.com/cnvs/studio/issues) that would help keep everything repo-specific. Thanks!
