### ISSUE TITLE
Limiting posting permission

### ISSUE THREAD

**Issue by jpmurray** [cnvs/canvas#754]
Hello!

I hope I'm just not misreading anything, or that my search skills fails me and I'm just repeating an already answered question but...

What would be the correct way to limit who can post articles ? I've quickly installed and glanced at canvas et studio, but my initial test made posting (and its relevant options) available to any registered account within the User model.

Say I want to limit posting to an admin, and only offer article to read for any guests and other users... What's the recommended way?

**Comment by austintoddj** [comment]
So the best way to limit this would be to add a new Middleware class to filter out whoever you want, and then add that middleware to the `config/canvas.php` file. 

Does that make sense?

**Comment by jpmurray** [comment]
It does!

Then I'd probably have to customize Studio so it doesn't show any menu or option to other user level (or not use Studio at all for that matter, but I'm a huge fan of simple things that works!), provided that I can make it so I don't overwrite my changes on updates... Right?

**Comment by austintoddj** [comment]
Glad it helped! And yes, you'd have to customize just a bit of Studio to get it to hide specific elements, but Studio is merely a starting-point template to get you up and running, totally up to you how to handle that side of things. 

As for Canvas, the [upgrade guide](https://github.com/cnvs/canvas/blob/master/.github/UPGRADE.md) will always be the single source of truth for any breaking changes, but you shouldn't have any trouble updating things in the future. 

Let me know if you've got any more questions about it!
