### ISSUE TITLE
how do i search post with underscore without writing underscore 

### ISSUE THREAD

**Issue by kama003** [cnvs/canvas#757]
Hey developers,
how do i search string with underscore without writing underscore 
example : someone searched xbox and there is post named x-box 
so now the problem is post doesn't appearing please help me to fix this

**Comment by ediblemanager** [comment]
Easiest solution would be to ensure that all posts relating to "xbox" have two tags: `x-box` and `xbox`.

Apart from this, you'll need to do some string comparison to work out if it's similar enough to match.

**Comment by austintoddj** [comment]
Closing this out since it's a generalized question and doesn't pertain to the project.
