### ISSUE TITLE
SEO settings doesn't work for search engine.

### ISSUE THREAD

**Issue by bakkan** [cnvs/canvas#758]
Post contents loaded by axios requests, the robots can't crawl anything from the pages.

**Comment by austintoddj** [comment]
Could you be more specific? Not sure what you mean by, "it can't crawl anything". Are the SEO elements loaded onto the page?

**Comment by bakkan** [comment]
I am sorry, my English is poor. SEO elements are not loaded.

https://medium.com/swlh/preloading-your-php-7-4-project-in-one-line-9ede756f292c
![image](https://user-images.githubusercontent.com/4957288/83151822-a0b56a00-a12f-11ea-9554-1d0e0015b504.png)
Using chrome view-source, you can find an `<h1>` element for the post title, a `<div>` element wrapper for the post body.

http://127.0.0.1:8000/studio/1/hello-world
View stutio pages , I can not see an `<h1>` element for the title and my post body.  the search engine robots doesn't know what about my post.

**Comment by austintoddj** [comment]
No worries @bakkan! So you cannot actually see any Meta tags passed on to the Post page in [Studio](https://github.com/cnvs/studio)?

**Comment by bakkan** [comment]
Yes, absolutely. Can you?
Look at this screenshot.
![image](https://user-images.githubusercontent.com/4957288/83163666-deb98a80-a13d-11ea-9a1d-d82463fed73b.png)
Ok, I will try to rewrite a [jquery-pjax](https://github.com/defunkt/jquery-pjax) version.
Thanks for you reply.

**Comment by austintoddj** [comment]
Ah, ok I see what it is.

In the [v5.2 upgrade](https://github.com/cnvs/canvas/blob/master/.github/UPGRADE.md#upgrading-to-520-from-51) of Canvas, we stopped saving `og:image`, `og:title`, `twitter:title` ...

Since that was just too granular, we slimmed down how the meta was saved. So, if you just adjust 
 your frontend files to pull those specific fields from the database, you'll be all set.

Let me know if that doesn't make sense.

**Comment by bakkan** [comment]
Studio is a SPA, every studio page has the same HTML contents.
`
<div id="studio" class="mb-5">
<router-view></router-view>
</div>
`
 Is it really good for SEO? There is no title, no keywords, no contents. How the spider understand my Post.
Have a good day, thanks again.

**Comment by austintoddj** [comment]
Studio uses [vue-headful](https://www.npmjs.com/package/vue-headful) to inject meta data into the head element of post pages. You can see it in the `PostScreen.vue` component:

```
<vue-headful
    v-if="isReady"
    :title="post.title + ' — Studio'"
    :description="post.summary"
    :image="post.featured_image"
    :url="meta.canonical_link"
/>
```

**Comment by albertoelias123** [comment]
Good afternoon Todd, I performed some tests on a website using the current version of Canvas (5.x) and the previous version that still didn't use a SPA. By my tests the SEO was drastically affected, now the search robots can no longer mine the information on the pages, researching I believe it is possible to get around this problem, but just using this headful of Vue does not seem to be enough.

Canvas previous version (without SPA)
![image](https://user-images.githubusercontent.com/41304037/84196651-e8fd5200-aa76-11ea-8150-421bade1cd9e.png)

Canvas current version (5.x)
![image](https://user-images.githubusercontent.com/41304037/84196691-f61a4100-aa76-11ea-8f08-cbceefef35f6.png)

As you can see by the Images, the Google robot understands ALL the Post's done on Canvas (5.x) as being the home page of Canvas / Studio. Do you have any idea how we can solve this difficulty? I would be happy to help
By the way, I was in doubt, where would it be more appropriate to post this Issue, here or on the Canvas/Studio repo?

**Comment by austintoddj** [comment]
@albertoelias123 Could you go ahead and make an issue for this in https://github.com/cnvs/studio

We can see about fixing it on that end. Thanks!
