### ISSUE TITLE
Enable social media sharing preview images

### ISSUE THREAD

**Issue by tj-mc** [cnvs/canvas#764]
When I share the link of a canvas post with Studio UI, sites like Facebook and Twitter are unable to fetch a preview image of the post content. Do you know of a way to enable this within canvas?

**Comment by austintoddj** [comment]
When you load a post up via Studio's UI, can you inspect the page and see if an `og:image` is visible in the head element?

**Comment by tj-mc** [comment]
Wow, in my hast I had deleted the Vue header component. Problem solved 🙏
