### ISSUE TITLE
Get tags in the order they are added

### ISSUE THREAD

**Issue by itsmysterybox** [cnvs/canvas#767]
I want to fetch the tags in the order they are added to the post.
Right now, if I add tags in following order

![image](https://user-images.githubusercontent.com/43930682/85827185-5f05f680-b7a3-11ea-81a1-ee3eca622a53.png)

I get

![image](https://user-images.githubusercontent.com/43930682/85827517-113dbe00-b7a4-11ea-9d39-e3279454fe1b.png)

I don't want to sort them with columns like `created_at`. Is there any way I can get the above order?

**Comment by austintoddj** [comment]
Is this in the SettingsModal itself that you want to see it ordered?

**Comment by itsmysterybox** [comment]
No. I'm fetching the associated tags on the front-end.

**Comment by austintoddj** [comment]
Unfortunately, we don't keep timestamps in the pivot tables. If we did, you could do some fancy query to order them by their `created_at` dates.

**Comment by itsmysterybox** [comment]
That can be tailored to meet my requirements. Thanks for your time.
