### ISSUE TITLE
Modify Slug post

### ISSUE THREAD

**Issue by ryanpram** [cnvs/canvas#788]
Hi how if i want to modify slug post with post title? for now the slug is using id which is not good for seo

**Comment by austintoddj** [comment]
When editing a post, go to the General Settings option, and you can make the slug anything you'd like.

**Comment by ryanpram** [comment]
Alright, i got it. Thankyou @austintoddj

**Comment by austintoddj** [comment]
No problem, thanks for checking out the package!
