### ISSUE TITLE
Embed Bootstrap snippets in the editor 

### ISSUE THREAD

**Issue by capricorn05** [cnvs/canvas#792]
Is it possible to add raw html to the page through the editor and then change it.  For example Id like to add a bootstrap card layout to a blog post.

**Comment by austintoddj** [comment]
Through the editor, you can embed pieces of code. So, you could drop in a Bootstrap card, and then you'd just have to make sure on the Frontend that you're pulling in the correct resources (ie. Bootstrap) to have it style correctly.

**Comment by capricorn05** [comment]
Yeah, I saw that option.  It quite messy as all spaces and indents cause the layout to be messed up.  I had to remove all spacing and indents and also manually add the images paths.  Its fine for me but for regular users it would be too difficult.  It would be ideal if there was a menu option that would allow you to add template and an option to view/edit the source.  Any plans for that

**Comment by austintoddj** [comment]
When you say the spaces and indents get all messy, do you mean the editor itself? I do know what you mean, it's really just a textarea where you drop in the snippet, which isn't ideal. A full-fledged code editor type thing would be great, and if I come across one that fits our needs then I'd have no problem at all integrating it. 

So, I'm on the lookout for one. Does that help?
